--------------------------------------------------------
--  DDL for Table FCSTDRAFT
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."FCSTDRAFT" 
   (	"DMDUNIT" VARCHAR2(50 CHAR), 
	"DMDGROUP" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"STARTDATE" DATE, 
	"DUR" NUMBER DEFAULT 1440, 
	"TYPE" NUMBER, 
	"FCSTID" VARCHAR2(50 CHAR), 
	"QTY" FLOAT(126) DEFAULT 0, 
	"MODEL" VARCHAR2(18 CHAR), 
	"LEWMEANQTY" FLOAT(126) DEFAULT 0, 
	"MARKETMGRVERSIONID" NUMBER(38,0) DEFAULT -1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
