--------------------------------------------------------
--  Constraints for Table FCSTTEMP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("STARTDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("MARKETMGRVERSIONID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("LEWMEANQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("FCSTID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("MODEL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("DMDGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("DMDUNIT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("BATCHNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."FCSTTEMP" MODIFY ("PROCESSID" NOT NULL ENABLE)
