--------------------------------------------------------
--  DDL for Table FCSTPERFSTATIC
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."FCSTPERFSTATIC" 
   (	"DMDUNIT" VARCHAR2(50 CHAR), 
	"DMDGROUP" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"FCSTDATE" DATE, 
	"STARTDATE" DATE, 
	"DUR" NUMBER(38,0), 
	"LAG" NUMBER DEFAULT 0, 
	"BASEHIST" FLOAT(126) DEFAULT 0, 
	"NONBASEHIST" FLOAT(126) DEFAULT 0, 
	"TOTHIST" FLOAT(126) DEFAULT 0, 
	"BASEFCST" FLOAT(126) DEFAULT 0, 
	"NONBASEFCST" FLOAT(126) DEFAULT 0, 
	"TOTFCST" FLOAT(126) DEFAULT 0, 
	"MAXBASEFCSTHIST" FLOAT(126) DEFAULT 0, 
	"MAXNONBASEFCSTHIST" FLOAT(126) DEFAULT 0, 
	"MAXTOTFCSTHIST" FLOAT(126) DEFAULT 0, 
	"BASEERROR" FLOAT(126) DEFAULT 0, 
	"NONBASEERROR" FLOAT(126) DEFAULT 0, 
	"TOTERROR" FLOAT(126) DEFAULT 0, 
	"ABSBASEERROR" FLOAT(126) DEFAULT 0, 
	"ABSNONBASEERROR" FLOAT(126) DEFAULT 0, 
	"ABSTOTERROR" FLOAT(126) DEFAULT 0, 
	"MODEL" VARCHAR2(18 CHAR), 
	"INTERNALEVENTS" FLOAT(126) DEFAULT 0, 
	"TOTFCSTLOCKADJ" FLOAT(126) DEFAULT 0, 
	"RECONCILEDFCST" FLOAT(126) DEFAULT 0, 
	"EXTERNALEVENTS" FLOAT(126) DEFAULT 0, 
	"FCSTOVERRIDE" FLOAT(126) DEFAULT 0, 
	"JOBID" NUMBER DEFAULT 0, 
	"USERID" VARCHAR2(256 CHAR) DEFAULT ' ', 
	"ABSPCTTOTERROR" FLOAT(126) DEFAULT 0, 
	"MARKETACTIVITY" FLOAT(126) DEFAULT 0, 
	"DATADRIVENEVENTS" FLOAT(126) DEFAULT 0, 
	"TARGETIMPACT" FLOAT(126) DEFAULT 0.0, 
	"DFUTOSKUFCST" FLOAT(126) DEFAULT 0.0, 
	"DFUTOSKUFCSTERROR" FLOAT(126) DEFAULT 0, 
	"ABSPCTDFUTOSKUFCSTERROR" FLOAT(126) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
