--------------------------------------------------------
--  DDL for Table FCSTORDER
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."FCSTORDER" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"NEEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"CALCPRIORITY" FLOAT(126) DEFAULT 0, 
	"CONSUMEDQTY" FLOAT(126) DEFAULT 0, 
	"MAXLATEDUR" NUMBER DEFAULT 0, 
	"PRIORITY" NUMBER DEFAULT -1, 
	"QTY" FLOAT(126) DEFAULT 0, 
	"SEQNUM" NUMBER(*,0), 
	"DUR" NUMBER(*,0) DEFAULT 0, 
	"MAXEARLYDUR" NUMBER(*,0) DEFAULT 0, 
	"PROJECT" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"PRIORITYSEQNUM" NUMBER(*,0) DEFAULT 0, 
	"ORDERTYPE" NUMBER(*,0) DEFAULT -125, 
	"ORDERSEQNUM" NUMBER DEFAULT 0, 
	"DMDTYPE" NUMBER(1,0) DEFAULT 1, 
	"EXPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY')
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
