--------------------------------------------------------
--  DDL for Index FCST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."FCST_PK" ON "SCPOMGR"."FCST" ("DMDUNIT", "DMDGROUP", "LOC", "STARTDATE", "TYPE", "FCSTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
