--------------------------------------------------------
--  DDL for Table FCSTORDERSTATUS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."FCSTORDERSTATUS" 
   (	"SCHEDQTY" FLOAT(126) DEFAULT 0, 
	"SCHEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SCHEDSTATUS" NUMBER(*,0), 
	"SEQNUM" NUMBER(*,0), 
	"ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"PROCESSSEQNUM" NUMBER(*,0), 
	"HASEXCEPTIONSW" NUMBER(1,0) DEFAULT 0, 
	"EXPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY')
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
