--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."ITEM" ADD CONSTRAINT "CHK_U_STOCK" CHECK (U_STOCK IN ('A', 'B', 'C')) DISABLE
  ALTER TABLE "SCPOMGR"."ITEM" ADD CONSTRAINT "ITEM_PK" PRIMARY KEY ("ITEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."ITEM" ADD CONSTRAINT "ALLOCPOLICY2" CHECK (ALLOCPOLICY IN (1, 2, 3)) ENABLE
  ALTER TABLE "SCPOMGR"."ITEM" ADD CONSTRAINT "INVOPTIMIZERTYPE" CHECK (InvOptimizerType IN (1, 2, 3)) ENABLE
  ALTER TABLE "SCPOMGR"."ITEM" ADD CONSTRAINT "BOOL_ITEM_DDSRCCOSTSW" CHECK (DDSRCCOSTSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."ITEM" ADD CONSTRAINT "BOOL_ITEM_DDSKUSW" CHECK (DDSKUSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."ITEM" ADD CONSTRAINT "BOOL_ITEM_PERISHABLESW" CHECK (PERISHABLESW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."ITEM" ADD CONSTRAINT "BOOL_ITEM_ENABLESW" CHECK (EnableSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("SUPSNGROUPNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("CALCCUMLEADTIMESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("ALLOCPOLICY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("DEFAULTUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("INVOPTIMIZERTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("ITEMCLASS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("DYNDEPQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("DYNDEPPUSHOPT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("DYNDEPOPTION" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("DYNDEPDECIMALS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("DDSRCCOSTSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("DDSKUSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("RESTRICTPLANMODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("PRIORITY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("PRIITEMPRIORITY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("PERISHABLESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("ENABLESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("PLANLEVEL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("UNITPRICE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("CANCELDEPTHLIMIT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("UNITSPERALTSHIP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("UNITSPERPALLET" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("VOL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("WGT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("UOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("DESCR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."ITEM" MODIFY ("ITEM" NOT NULL ENABLE)
