--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."ITEM" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"DESCR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"UOM" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"WGT" FLOAT(126) DEFAULT 0, 
	"VOL" FLOAT(126) DEFAULT 0, 
	"UNITSPERPALLET" FLOAT(126) DEFAULT 1, 
	"UNITSPERALTSHIP" FLOAT(126) DEFAULT 1, 
	"CANCELDEPTHLIMIT" NUMBER DEFAULT 0, 
	"UNITPRICE" FLOAT(126) DEFAULT 0, 
	"PLANLEVEL" NUMBER(38,0) DEFAULT -1, 
	"ENABLESW" NUMBER(1,0) DEFAULT 1, 
	"PERISHABLESW" NUMBER(1,0) DEFAULT 0, 
	"PRIITEMPRIORITY" NUMBER(38,0) DEFAULT 0, 
	"PRIORITY" NUMBER(*,0) DEFAULT 1, 
	"RESTRICTPLANMODE" NUMBER(*,0) DEFAULT 1, 
	"DDSKUSW" NUMBER(1,0) DEFAULT 0, 
	"DDSRCCOSTSW" NUMBER(1,0) DEFAULT 0, 
	"DYNDEPDECIMALS" NUMBER(*,0) DEFAULT 0, 
	"DYNDEPOPTION" NUMBER(*,0) DEFAULT 1, 
	"DYNDEPPUSHOPT" NUMBER(*,0) DEFAULT 1, 
	"DYNDEPQTY" FLOAT(126) DEFAULT 1, 
	"FF_TRIGGER_CONTROL" NUMBER(*,0), 
	"ITEMCLASS" VARCHAR2(50 CHAR) DEFAULT 'DEFAULT', 
	"INVOPTIMIZERTYPE" NUMBER DEFAULT 1, 
	"DEFAULTUOM" NUMBER(*,0) DEFAULT 18, 
	"ALLOCPOLICY" NUMBER(1,0) DEFAULT 1, 
	"CALCCUMLEADTIMESW" NUMBER(1,0) DEFAULT 0, 
	"SUPSNGROUPNUM" NUMBER DEFAULT -1, 
	"U_MATERIALCODE" VARCHAR2(10 CHAR), 
	"U_QUALITYBATCH" VARCHAR2(20 CHAR), 
	"U_STOCK" VARCHAR2(1 CHAR), 
	"U_FREIGHT_FACTOR" NUMBER DEFAULT 0.0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
