--------------------------------------------------------
--  DDL for Table LOC
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."LOC" 
   (	"LOC" VARCHAR2(50 CHAR), 
	"DESCR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"OHPOST" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"FRZSTART" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SOURCECAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"DESTCAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"TYPE" NUMBER(*,0) DEFAULT 1, 
	"ALTPLANTID" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"CUST" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"TRANSZONE" VARCHAR2(18 CHAR) DEFAULT ' ', 
	"LAT" FLOAT(126) DEFAULT 0, 
	"LON" FLOAT(126) DEFAULT 0, 
	"ENABLESW" NUMBER(1,0) DEFAULT 1, 
	"FF_TRIGGER_CONTROL" NUMBER(*,0), 
	"LOC_TYPE" NUMBER(*,0) DEFAULT 6.0, 
	"VENDID" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"COMPANYID" VARCHAR2(50 CHAR) DEFAULT '', 
	"WORKINGCAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"SEQINTEXPORTDUR" NUMBER(*,0) DEFAULT 0, 
	"SEQINTIMPORTDUR" NUMBER(*,0) DEFAULT 0, 
	"SEQINTLASTEXPORTEDTOSEQ" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SEQINTLASTIMPORTEDFROMSEQ" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"POSTALCODE" VARCHAR2(10 CHAR) DEFAULT 0, 
	"COUNTRY" VARCHAR2(20 CHAR) DEFAULT ' ', 
	"CURRENCY" VARCHAR2(5 CHAR) DEFAULT ' ', 
	"WDDAREA" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"BORROWINGPCT" FLOAT(126) DEFAULT 0, 
	"HIERARCHYLEVEL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_LOCTYPE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_CITY" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_COUNTRYDES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_GEOCODE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SALESDIR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SALESDIRDES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SALESMAN" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SALESMANDES" VARCHAR2(50 CHAR) DEFAULT '50', 
	"U_3DIGITZIP" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_STATE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_AREA" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_REGION" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_PARENT" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_PARENT_DES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SUBAFFIL" VARCHAR2(50 CHAR) DEFAULT '50', 
	"U_GRANDPARENT" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_GRANDPARENT_DES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_AFFIL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_CUSTTYPE" VARCHAR2(50 CHAR) DEFAULT 'P', 
	"U_CGROUP" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_INDUSTRY" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_MKTSECTOR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_MKTSECTOR_DES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_MAX_SRC" NUMBER(10,0) DEFAULT 3, 
	"U_MAX_DIST" NUMBER(10,0) DEFAULT 150, 
	"U_PRODUCT_SPECIALITY" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_PLANT_NETWORK_TYPE" VARCHAR2(20 CHAR), 
	"U_SALES_SECTOR" VARCHAR2(100 CHAR), 
	"U_TERRITORY" VARCHAR2(100 CHAR) DEFAULT 'UNASSIGNED_PNO', 
	"U_PLANTGROUP" VARCHAR2(50 CHAR) DEFAULT 'SC', 
	"U_CLOSINGDATE" DATE, 
	"U_EQUIPMENT_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_RUNEW_CUST" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."LOC"."LOC" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."LOC"."LOC_TYPE" IS 'Standard Location Types                                   1. Supplier                                                          2. Plant                                                               3. Distribution Center (DC)                                     4. Customer'
   COMMENT ON COLUMN "SCPOMGR"."LOC"."WORKINGCAL" IS 'Unique identifier / name for the calendar'
