--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOC
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."LOC" 
   (	"LOC" VARCHAR2(50 CHAR), 
	"DESCR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"OHPOST" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"FRZSTART" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SOURCECAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"DESTCAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"TYPE" NUMBER(*,0) DEFAULT 1, 
	"ALTPLANTID" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"CUST" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"TRANSZONE" VARCHAR2(18 CHAR) DEFAULT ' ', 
	"LAT" FLOAT(126) DEFAULT 0, 
	"LON" FLOAT(126) DEFAULT 0, 
	"ENABLESW" NUMBER(1,0) DEFAULT 1, 
	"FF_TRIGGER_CONTROL" NUMBER(*,0), 
	"LOC_TYPE" NUMBER(*,0) DEFAULT 6.0, 
	"VENDID" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"COMPANYID" VARCHAR2(50 CHAR) DEFAULT '', 
	"WORKINGCAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"SEQINTEXPORTDUR" NUMBER(*,0) DEFAULT 0, 
	"SEQINTIMPORTDUR" NUMBER(*,0) DEFAULT 0, 
	"SEQINTLASTEXPORTEDTOSEQ" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SEQINTLASTIMPORTEDFROMSEQ" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"POSTALCODE" VARCHAR2(10 CHAR) DEFAULT 0, 
	"COUNTRY" VARCHAR2(20 CHAR) DEFAULT ' ', 
	"CURRENCY" VARCHAR2(5 CHAR) DEFAULT ' ', 
	"WDDAREA" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"BORROWINGPCT" FLOAT(126) DEFAULT 0, 
	"HIERARCHYLEVEL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_LOCTYPE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_CITY" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_COUNTRYDES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_GEOCODE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SALESDIR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SALESDIRDES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SALESMAN" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SALESMANDES" VARCHAR2(50 CHAR) DEFAULT '50', 
	"U_3DIGITZIP" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_STATE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_AREA" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_REGION" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_PARENT" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_PARENT_DES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_SUBAFFIL" VARCHAR2(50 CHAR) DEFAULT '50', 
	"U_GRANDPARENT" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_GRANDPARENT_DES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_AFFIL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_CUSTTYPE" VARCHAR2(50 CHAR) DEFAULT 'P', 
	"U_CGROUP" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_INDUSTRY" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_MKTSECTOR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_MKTSECTOR_DES" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_MAX_SRC" NUMBER(10,0) DEFAULT 3, 
	"U_MAX_DIST" NUMBER(10,0) DEFAULT 150, 
	"U_PRODUCT_SPECIALITY" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_PLANT_NETWORK_TYPE" VARCHAR2(20 CHAR), 
	"U_SALES_SECTOR" VARCHAR2(100 CHAR), 
	"U_TERRITORY" VARCHAR2(100 CHAR) DEFAULT 'UNASSIGNED_PNO', 
	"U_PLANTGROUP" VARCHAR2(50 CHAR) DEFAULT 'SC', 
	"U_CLOSINGDATE" DATE, 
	"U_EQUIPMENT_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"U_RUNEW_CUST" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;

   COMMENT ON COLUMN "SCPOMGR"."LOC"."LOC" IS ' ';
   COMMENT ON COLUMN "SCPOMGR"."LOC"."LOC_TYPE" IS 'Standard Location Types                                   1. Supplier                                                          2. Plant                                                               3. Distribution Center (DC)                                     4. Customer';
   COMMENT ON COLUMN "SCPOMGR"."LOC"."WORKINGCAL" IS 'Unique identifier / name for the calendar';
--------------------------------------------------------
--  DDL for Index LOC_BIDX
--------------------------------------------------------

  CREATE BITMAP INDEX "SCPOMGR"."LOC_BIDX" ON "SCPOMGR"."LOC" ("U_AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index XIF1LOC
--------------------------------------------------------

  CREATE INDEX "SCPOMGR"."XIF1LOC" ON "SCPOMGR"."LOC" ("SOURCECAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index XIF2LOC
--------------------------------------------------------

  CREATE INDEX "SCPOMGR"."XIF2LOC" ON "SCPOMGR"."LOC" ("DESTCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index XIF3LOC
--------------------------------------------------------

  CREATE INDEX "SCPOMGR"."XIF3LOC" ON "SCPOMGR"."LOC" ("LOC_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index LOC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."LOC_PK" ON "SCPOMGR"."LOC" ("LOC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table LOC
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_LOC_TYPE" CHECK (LOC_TYPE IN (1,2,3,4,6)) ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_U_RUNEW_CUST" CHECK (U_RUNEW_CUST IN (0,1)) ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_RUNEW_CUST" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_TERRITORY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_PRODUCT_SPECIALITY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_MKTSECTOR_DES" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_MKTSECTOR" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_INDUSTRY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_CGROUP" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_CUSTTYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_AFFIL" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_GRANDPARENT_DES" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_GRANDPARENT" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SUBAFFIL" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_PARENT_DES" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_PARENT" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_REGION" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_AREA" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_STATE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_3DIGITZIP" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SALESMANDES" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SALESMAN" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SALESDIRDES" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SALESDIR" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_GEOCODE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_COUNTRYDES" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_CITY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_LOCTYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("HIERARCHYLEVEL" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_LOC_BORROWINGPCT" CHECK (BorrowingPct >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("BORROWINGPCT" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("WDDAREA" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_PK" PRIMARY KEY ("LOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_LOC_EXTRACT_DUR" CHECK (SeqIntImportDur >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_LOC_EXPORT_DUR" CHECK (SeqIntExportDur >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "BOOL_LOC_ENABLESW" CHECK (EnableSw IN (0, 1)) ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LAT_LON" CHECK (Lon BETWEEN -180 AND 180) ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LATITUDE_RANGE" CHECK (Lat BETWEEN -90 AND 90) ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SEQINTLASTIMPORTEDFROMSEQ" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SEQINTLASTEXPORTEDTOSEQ" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SEQINTIMPORTDUR" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SEQINTEXPORTDUR" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("WORKINGCAL" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("COMPANYID" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("VENDID" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("LOC_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("ENABLESW" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("LON" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("LAT" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("TRANSZONE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("CUST" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("ALTPLANTID" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("DESTCAL" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SOURCECAL" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("FRZSTART" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("OHPOST" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("DESCR" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("LOC" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LOC
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "FK_UDT_LOC_TYPE" FOREIGN KEY ("LOC_TYPE")
	  REFERENCES "SCPOMGR"."UDT_LOC_TYPE" ("LOC_TYPE") ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_CAL_FK1" FOREIGN KEY ("SOURCECAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_CAL_FK2" FOREIGN KEY ("DESTCAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_CAL_FK3" FOREIGN KEY ("WORKINGCAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_LOCTYPE_FK1" FOREIGN KEY ("LOC_TYPE")
	  REFERENCES "SCPOMGR"."LOCTYPE" ("TYPE") ENABLE;
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_WDDAREA_FK1" FOREIGN KEY ("WDDAREA")
	  REFERENCES "SCPOMGR"."WDDAREA" ("WDDAREA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCPROTECTPHTRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCPOMGR"."LOCPROTECTPHTRIG" 
before delete on LOC for each row
begin
  if :old.LOC = ' ' then
     RAISE_APPLICATION_ERROR
        (-20001, 'Cannot delete LOC record with blank LOC column');
  end if;
end;
/
ALTER TRIGGER "SCPOMGR"."LOCPROTECTPHTRIG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIU_PLANNETCHG_LOC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCPOMGR"."TIU_PLANNETCHG_LOC" 
BEFORE INSERT OR UPDATE ON LOC
for each row
   WHEN (NEW.FF_TRIGGER_CONTROL IS NOT NULL) BEGIN

   if INSERTING THEN
      -- set netchangesw if not already set
      UPDATE sku SET netchgsw = 1
         WHERE  netchgsw = 0
            AND   sku.loc = :new.loc;

    elsif UPDATING then
        if :NEW.FF_TRIGGER_CONTROL=-1 then
          UPDATE sku SET netchgsw = 1
            WHERE  netchgsw = 0
            AND   sku.loc = :new.loc;
      elsif
        -- set netchangesw if ohpost, frzstart columns have changed
        :new.ohpost <> :old.ohpost or
        :new.frzstart <> :old.frzstart
      then
        -- set netchangesw if not already set
        UPDATE sku SET netchgsw = 1
            WHERE netchgsw = 0
            AND   sku.loc = :new.loc;
      end if;
  end if;

   -- reset trigger_control to NULL
   :new.FF_TRIGGER_CONTROL := NULL;

END;
/
ALTER TRIGGER "SCPOMGR"."TIU_PLANNETCHG_LOC" ENABLE;
