--------------------------------------------------------
--  Ref Constraints for Table LOC
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "FK_UDT_LOC_TYPE" FOREIGN KEY ("LOC_TYPE")
	  REFERENCES "SCPOMGR"."UDT_LOC_TYPE" ("LOC_TYPE") ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_CAL_FK1" FOREIGN KEY ("SOURCECAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_CAL_FK2" FOREIGN KEY ("DESTCAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_CAL_FK3" FOREIGN KEY ("WORKINGCAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_LOCTYPE_FK1" FOREIGN KEY ("LOC_TYPE")
	  REFERENCES "SCPOMGR"."LOCTYPE" ("TYPE") ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_WDDAREA_FK1" FOREIGN KEY ("WDDAREA")
	  REFERENCES "SCPOMGR"."WDDAREA" ("WDDAREA") ENABLE
