--------------------------------------------------------
--  Constraints for Table LOC
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_LOC_TYPE" CHECK (LOC_TYPE IN (1,2,3,4,6)) ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_U_RUNEW_CUST" CHECK (U_RUNEW_CUST IN (0,1)) ENABLE
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_RUNEW_CUST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_TERRITORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_PRODUCT_SPECIALITY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_MKTSECTOR_DES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_MKTSECTOR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_INDUSTRY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_CGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_CUSTTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_AFFIL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_GRANDPARENT_DES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_GRANDPARENT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SUBAFFIL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_PARENT_DES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_PARENT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_REGION" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_AREA" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_STATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_3DIGITZIP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SALESMANDES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SALESMAN" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SALESDIRDES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_SALESDIR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_GEOCODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_COUNTRYDES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_CITY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("U_LOCTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("HIERARCHYLEVEL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_LOC_BORROWINGPCT" CHECK (BorrowingPct >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("BORROWINGPCT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("WDDAREA" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("CURRENCY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LOC_PK" PRIMARY KEY ("LOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_LOC_EXTRACT_DUR" CHECK (SeqIntImportDur >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "CHK_LOC_EXPORT_DUR" CHECK (SeqIntExportDur >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "BOOL_LOC_ENABLESW" CHECK (EnableSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LAT_LON" CHECK (Lon BETWEEN -180 AND 180) ENABLE
  ALTER TABLE "SCPOMGR"."LOC" ADD CONSTRAINT "LATITUDE_RANGE" CHECK (Lat BETWEEN -90 AND 90) ENABLE
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SEQINTLASTIMPORTEDFROMSEQ" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SEQINTLASTEXPORTEDTOSEQ" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SEQINTIMPORTDUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SEQINTEXPORTDUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("WORKINGCAL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("VENDID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("LOC_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("ENABLESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("LON" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("LAT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("TRANSZONE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("CUST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("ALTPLANTID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("DESTCAL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("SOURCECAL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("FRZSTART" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("OHPOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("DESCR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."LOC" MODIFY ("LOC" NOT NULL ENABLE)
