--------------------------------------------------------
--  Constraints for Table MAK_SKUCONSTR_NO_5ZIP_COSTTRN
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTR_NO_5ZIP_COSTTRN" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTR_NO_5ZIP_COSTTRN" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTR_NO_5ZIP_COSTTRN" MODIFY ("ITEM" NOT NULL ENABLE)
