--------------------------------------------------------
--  DDL for Table MAK_SKUCONSTR_NO_5ZIP_COLL
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."MAK_SKUCONSTR_NO_5ZIP_COLL" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"TOTALCOLLECTION" NUMBER, 
	"POSTALCODE" VARCHAR2(10 CHAR), 
	"U_EQUIPMENT_TYPE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
