--------------------------------------------------------
--  Constraints for Table MAK_SKUCONSTR_NO_5ZIP_COLL
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTR_NO_5ZIP_COLL" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTR_NO_5ZIP_COLL" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."MAK_SKUCONSTR_NO_5ZIP_COLL" MODIFY ("ITEM" NOT NULL ENABLE)
