--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONYIELD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONYIELD" ADD CONSTRAINT "PRODUCTIONYIELD_SKU_FK2" FOREIGN KEY ("OUTPUTITEM", "LOC")
	  REFERENCES "SCPOMGR"."SKU" ("ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONYIELD" ADD CONSTRAINT "PRODYIELD_PRODMETHOD_FK1" FOREIGN KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
	  REFERENCES "SCPOMGR"."PRODUCTIONMETHOD" ("PRODUCTIONMETHOD", "ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONYIELD" ADD CONSTRAINT "PRODYIELD_UOM_FK1" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
