--------------------------------------------------------
--  DDL for Index PRODUCTIONFAMILYSKULOAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."PRODUCTIONFAMILYSKULOAD_PK" ON "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" ("PLANNAME", "RES", "PRODFAMILY", "STARTDATE", "SEQNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"
