--------------------------------------------------------
--  Ref Constraints for Table PRODPROJ
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODPROJ" ADD CONSTRAINT "PRODPROJ_PRODUCTIONMETHOD_FK1" FOREIGN KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
	  REFERENCES "SCPOMGR"."PRODUCTIONMETHOD" ("PRODUCTIONMETHOD", "ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODPROJ" ADD CONSTRAINT "PRODPROJ_SKU_FK1" FOREIGN KEY ("ITEM", "LOC")
	  REFERENCES "SCPOMGR"."SKU" ("ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODPROJ" ADD CONSTRAINT "PRODPROJ_UOM_FK1" FOREIGN KEY ("NUMERATORUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODPROJ" ADD CONSTRAINT "PRODPROJ_UOM_FK2" FOREIGN KEY ("DENOMINATORUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODPROJ" ADD CONSTRAINT "PRODPROJ_UOM_FK3" FOREIGN KEY ("ADDITIONALUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
