--------------------------------------------------------
--  Constraints for Table PRODUCTIONFAMILYRESMAP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYRESMAP" ADD CONSTRAINT "XPKPRODUCTIONFAMILYRESMAP" PRIMARY KEY ("ORGRES", "PRODFAMILY", "NEWRES", "SIMULATION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYRESMAP" MODIFY ("SIMULATION_NAME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYRESMAP" MODIFY ("NEWRES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYRESMAP" MODIFY ("PRODFAMILY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYRESMAP" MODIFY ("ORGRES" NOT NULL ENABLE)
