--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONFAMILYSKULOAD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" ADD CONSTRAINT "PRDFAMLYSKULOAD_PRODFAMILY_FK" FOREIGN KEY ("PRODFAMILY")
	  REFERENCES "SCPOMGR"."PRODUCTIONFAMILY" ("PRODFAMILY") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" ADD CONSTRAINT "PRDUCTIONFAMILYSKULOAD_RES_FK" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ENABLE
