--------------------------------------------------------
--  Constraints for Table PRODITEMPROJ
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "PRODITEMPROJ_PK" PRIMARY KEY ("PRODUCTIONMETHOD", "ITEM", "PRODUCTIONMETHODITEM", "LOC", "TVQCATEGORY", "EFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "CHK_PRDITMPROJ_DUR" CHECK (DUR >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "CONSTRAINT_POLICY" CHECK (POLICY IN (0, 1, 2)) ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "CHK_PRDITMPROJ_ADDITIONALUOM" CHECK (ADDITIONALUOM >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "CHK_PRDITMPROJ_DENOMINATORUOM" CHECK (DENOMINATORUOM >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "CHK_PRDITMPROJ_NUMERATORUOM" CHECK (NUMERATORUOM >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("POLICY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("OPTIONSETNAME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("ADDITIONALUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("DENOMINATORUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("TVQCATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("NUMERATORUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("PRODUCTIONMETHODITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
