--------------------------------------------------------
--  Constraints for Table PRODUCTIONRESMETRIC
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" ADD CONSTRAINT "XPKPRODUCTIONRESMETRIC" PRIMARY KEY ("CATEGORY", "PRODUCTIONMETHOD", "ITEM", "LOC", "RES", "EFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" ADD CONSTRAINT "CHK_PRODUCTIONRESMETRIC_DUR" CHECK (Dur >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONRESMETRIC" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
