--------------------------------------------------------
--  DDL for Table PRODUCTIONFAMILYLOAD
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PRODUCTIONFAMILYLOAD" 
   (	"PLANNAME" VARCHAR2(50 CHAR), 
	"RES" VARCHAR2(101 CHAR), 
	"PRODFAMILY" VARCHAR2(50 CHAR), 
	"CHGOVERPRODFAMILY" VARCHAR2(50 CHAR), 
	"STARTDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"LOAD" FLOAT(126) DEFAULT 0.0, 
	"CHGOVEROCCUR" NUMBER(1,0) DEFAULT 0, 
	"LOADSEQNUM" NUMBER DEFAULT 0, 
	"CHANGEOVERLOAD" FLOAT(126) DEFAULT 0, 
	"ISFIRMLOAD" NUMBER(1,0) DEFAULT 0, 
	"ALLOCCAP" FLOAT(126) DEFAULT 0.0, 
	"DUR" NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SCPODATA"
