--------------------------------------------------------
--  DDL for Table PRODUCTIONCOST
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PRODUCTIONCOST" 
   (	"CATEGORY" NUMBER(*,0), 
	"PRODUCTIONMETHOD" VARCHAR2(50 CHAR), 
	"LOCALCOST" VARCHAR2(110 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"ITEM" VARCHAR2(50 CHAR), 
	"TIEREDCOST" VARCHAR2(110 CHAR) DEFAULT ' '
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONCOST"."CATEGORY" IS ' '
