--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONCOST
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONCOST" ADD CONSTRAINT "PRODCOST_COSTCATEGORY_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCPOMGR"."COSTCATEGORY" ("CATEGORY") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONCOST" ADD CONSTRAINT "PRODCOST_PRODMETHOD_FK1" FOREIGN KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
	  REFERENCES "SCPOMGR"."PRODUCTIONMETHOD" ("PRODUCTIONMETHOD", "ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONCOST" ADD CONSTRAINT "PRODUCTIONCOST_COST_FK1" FOREIGN KEY ("LOCALCOST")
	  REFERENCES "SCPOMGR"."COST" ("COST") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONCOST" ADD CONSTRAINT "PRODUCTIONCOST_COST_FK2" FOREIGN KEY ("TIEREDCOST")
	  REFERENCES "SCPOMGR"."COST" ("COST") ENABLE
