--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONMETHOD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "PRODMETHOD_FINISHCAL_FK" FOREIGN KEY ("FINISHCAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "PRODMETHOD_LEADTIMECAL_FK" FOREIGN KEY ("LEADTIMECAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "PRODUCTIONMETHOD_SKU_FK1" FOREIGN KEY ("ITEM", "LOC")
	  REFERENCES "SCPOMGR"."SKU" ("ITEM", "LOC") ON DELETE CASCADE ENABLE
