--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONFAMILYCHGOVER
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYCHGOVER" ADD CONSTRAINT "PRDFAMILYCHGOVER_PRDFAMILY_FK1" FOREIGN KEY ("FROMFAMILY")
	  REFERENCES "SCPOMGR"."PRODUCTIONFAMILY" ("PRODFAMILY") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYCHGOVER" ADD CONSTRAINT "PRDFAMILYCHGOVER_PRDFAMILY_FK2" FOREIGN KEY ("TOFAMILY")
	  REFERENCES "SCPOMGR"."PRODUCTIONFAMILY" ("PRODFAMILY") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYCHGOVER" ADD CONSTRAINT "PRODFAMILYCHGOVER_RES_FK" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ON DELETE CASCADE ENABLE
