--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONCONSTRAINT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONCONSTRAINT" ADD CONSTRAINT "PRODCONSTRAINT_CONSTRCAT_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCPOMGR"."CONSTRAINTCATEGORY" ("CATEGORY") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONCONSTRAINT" ADD CONSTRAINT "PRODCONSTRAINT_PRODMETHOD_FK1" FOREIGN KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
	  REFERENCES "SCPOMGR"."PRODUCTIONMETHOD" ("PRODUCTIONMETHOD", "ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONCONSTRAINT" ADD CONSTRAINT "PRODCONSTRAINT_UOM_FK1" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONCONSTRAINT" ADD CONSTRAINT "PRODUCTIONCONSTRAINT_SKU_FK1" FOREIGN KEY ("OUTPUTITEM", "LOC")
	  REFERENCES "SCPOMGR"."SKU" ("ITEM", "LOC") ON DELETE CASCADE ENABLE
