--------------------------------------------------------
--  Ref Constraints for Table PRODITEMPROJ
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "PRODITEMPROJ_ITEM_FK1" FOREIGN KEY ("PRODUCTIONMETHODITEM")
	  REFERENCES "SCPOMGR"."ITEM" ("ITEM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "PRODITEMPROJ_UOM_FK1" FOREIGN KEY ("NUMERATORUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "PRODITEMPROJ_UOM_FK2" FOREIGN KEY ("DENOMINATORUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODITEMPROJ" ADD CONSTRAINT "PRODITEMPROJ_UOM_FK3" FOREIGN KEY ("ADDITIONALUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
