--------------------------------------------------------
--  DDL for Table PRODUCTIONMETHOD
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PRODUCTIONMETHOD" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"PRODUCTIONMETHOD" VARCHAR2(50 CHAR), 
	"DESCR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"EFF" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"PRIORITY" NUMBER DEFAULT 1, 
	"MINQTY" FLOAT(126) DEFAULT 0, 
	"INCQTY" FLOAT(126) DEFAULT 0, 
	"DISC" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"LEADTIME" NUMBER DEFAULT 0, 
	"MAXQTY" FLOAT(126) DEFAULT 0, 
	"OFFSETTYPE" NUMBER DEFAULT 1, 
	"LOADOPT" NUMBER DEFAULT 1, 
	"MAXSTARTDUR" NUMBER(38,0) DEFAULT 0, 
	"MAXFINDUR" NUMBER(38,0) DEFAULT 0, 
	"SPLITORDERSW" NUMBER(1,0) DEFAULT 0, 
	"BOMNUM" NUMBER(38,0) DEFAULT 0, 
	"ENABLESW" NUMBER(1,0) DEFAULT 1, 
	"MINLEADTIME" NUMBER(*,0) DEFAULT 0, 
	"MAXLEADTIME" NUMBER(*,0) DEFAULT 1440 * 365 * 100, 
	"YIELDQTY" FLOAT(126) DEFAULT 0, 
	"SPLITFACTOR" FLOAT(126) DEFAULT 1, 
	"NONEWSUPPLYDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"FINISHCAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"LEADTIMECAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"WORKSCOPE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"LOTSIZESENABLEDSW" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONMETHOD"."ENABLESW" IS 'This switch will enable/disable this production method for a run of the optimize. If this switch is false, the optimizer will ignore this production method.'
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONMETHOD"."MINLEADTIME" IS 'Minimum production lead time for this production method, specified in minutes.'
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONMETHOD"."MAXLEADTIME" IS 'The maximum production lead time for this production method, specified in minutes.'
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONMETHOD"."YIELDQTY" IS 'Yield Qty of the primary SKU (item, loc) for this production method.'
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONMETHOD"."FINISHCAL" IS 'Unique identifier / name for the calendar'
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONMETHOD"."LEADTIMECAL" IS 'Unique identifier / name for the calendar'
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONMETHOD"."WORKSCOPE" IS 'Distinctly selects a routing method in FRP during resource loading for PSOs'
   COMMENT ON TABLE "SCPOMGR"."PRODUCTIONMETHOD"  IS 'The ProductionMethod table defines the production methods (i.e. make processes) for the model.'
