--------------------------------------------------------
--  Constraints for Table PRODUCTIONFAMILYSKULOAD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" ADD CONSTRAINT "PRODUCTIONFAMILYSKULOAD_PK" PRIMARY KEY ("PLANNAME", "RES", "PRODFAMILY", "STARTDATE", "SEQNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("ORGWHENLOADED" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("LOADSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("SUPPLYTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("STEPNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("LOAD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("SEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("STARTDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("PRODFAMILY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONFAMILYSKULOAD" MODIFY ("PLANNAME" NOT NULL ENABLE)
