--------------------------------------------------------
--  DDL for Table PRODUCTIONCONSTRAINT
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PRODUCTIONCONSTRAINT" 
   (	"PRODUCTIONMETHOD" VARCHAR2(50 CHAR), 
	"EFF" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"POLICY" NUMBER(*,0) DEFAULT 0, 
	"QTY" FLOAT(126), 
	"DUR" NUMBER(*,0) DEFAULT 0, 
	"CATEGORY" NUMBER(*,0), 
	"ITEM" VARCHAR2(50 CHAR), 
	"OUTPUTITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"QTYUOM" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONCONSTRAINT"."CATEGORY" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONCONSTRAINT"."LOC" IS ' '
