--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONMETRIC
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONMETRIC" ADD CONSTRAINT "PRODMETRIC_METRICCATEGORY_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCPOMGR"."METRICCATEGORY" ("CATEGORY") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETRIC" ADD CONSTRAINT "PRODMETRIC_PRODMETHOD_FK1" FOREIGN KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
	  REFERENCES "SCPOMGR"."PRODUCTIONMETHOD" ("PRODUCTIONMETHOD", "ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETRIC" ADD CONSTRAINT "PRODUCTIONMETRIC_CURRUOM_FK" FOREIGN KEY ("CURRENCYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETRIC" ADD CONSTRAINT "PRODUCTIONMETRIC_QTYUOM_FK" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETRIC" ADD CONSTRAINT "PRODUCTIONMETRIC_SKU_FK1" FOREIGN KEY ("OUTPUTITEM", "LOC")
	  REFERENCES "SCPOMGR"."SKU" ("ITEM", "LOC") ON DELETE CASCADE ENABLE
