--------------------------------------------------------
--  DDL for Table PRODUCTIONTARGET
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PRODUCTIONTARGET" 
   (	"PRODUCTIONMETHOD" VARCHAR2(50 CHAR), 
	"ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"OUTPUTITEM" VARCHAR2(50 CHAR), 
	"EFF" DATE DEFAULT TO_DATE('01/01/2003','MM/DD/YYYY'), 
	"DISC" DATE DEFAULT TO_DATE('01/01/2003','MM/DD/YYYY'), 
	"QTY" FLOAT(126) DEFAULT 0.0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SCPODATA"
