--------------------------------------------------------
--  DDL for Table PRODUCTIONFAMILYRESMAP
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PRODUCTIONFAMILYRESMAP" 
   (	"ORGRES" VARCHAR2(101 CHAR), 
	"PRODFAMILY" VARCHAR2(50 CHAR), 
	"NEWRES" VARCHAR2(101 CHAR), 
	"SIMULATION_NAME" VARCHAR2(50 CHAR) DEFAULT 'LIVE'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SCPODATA"
