--------------------------------------------------------
--  Constraints for Table PRODUCTIONLEADTIME
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONLEADTIME" ADD CONSTRAINT "XPKPRODUCTIONLEADTIME" PRIMARY KEY ("PRODUCTIONMETHOD", "EFF", "ITEM", "LOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONLEADTIME" ADD CONSTRAINT "CHK_PRODLEADTIME_CALCLEADTIME" CHECK (CalcLeadTime >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONLEADTIME" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONLEADTIME" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONLEADTIME" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONLEADTIME" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONLEADTIME" MODIFY ("CALCLEADTIME" NOT NULL ENABLE)
