--------------------------------------------------------
--  Constraints for Table PRODUCTIONMETHOD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("LOTSIZESENABLEDSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "PRODUCTIONMETHOD_PK" PRIMARY KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "PERCENTAGE6" CHECK (SplitFactor BETWEEN 0.0 AND 100.0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "CHK_PRODNMETHOD_MAXLEADTIME" CHECK (MaxLeadTime >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "CHK_PRODNMETHOD_MINLEADTIME" CHECK (MinLeadTime >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "BOOL_PRODMETHOD_ENABLESW" CHECK (EnableSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "VALID_BOMNUM" CHECK (BOMNUM >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "BOOL_PRODMETHOD_SPLITORDERSW" CHECK (SPLITORDERSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "CHK_PRODNMETHOD_MAXFINDUR" CHECK (MAXFINDUR >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "CHK_PRODNMETHOD_MAXSTARTDUR" CHECK (MAXSTARTDUR >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "LOADOPT" CHECK (LOADOPT IN (1, 2, 3, 4, 5)) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "OFFSETTYPE" CHECK (OFFSETTYPE IN (1, 2, 3)) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" ADD CONSTRAINT "CHK_PRODNMETHOD_LEADTIME" CHECK (LEADTIME >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("WORKSCOPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("LEADTIMECAL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("FINISHCAL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("NONEWSUPPLYDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("SPLITFACTOR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("YIELDQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("MAXLEADTIME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("MINLEADTIME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("ENABLESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("BOMNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("SPLITORDERSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("MAXFINDUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("MAXSTARTDUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("LOADOPT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("OFFSETTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("MAXQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("LEADTIME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("DISC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("INCQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("MINQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("PRIORITY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("DESCR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."PRODUCTIONMETHOD" MODIFY ("ITEM" NOT NULL ENABLE)
