--------------------------------------------------------
--  DDL for Table PRODUCTIONFAMILY
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PRODUCTIONFAMILY" 
   (	"PRODFAMILY" VARCHAR2(50 CHAR), 
	"DESCR" VARCHAR2(50 CHAR), 
	"MINPRODDUR" NUMBER DEFAULT 1440, 
	"INCPRODDUR" NUMBER DEFAULT 1440, 
	"MAXPRODDUR" NUMBER DEFAULT 0, 
	"SEQNUM" NUMBER DEFAULT 0, 
	"MINPRODLOAD" FLOAT(126) DEFAULT 0, 
	"INCPRODLOAD" FLOAT(126) DEFAULT 0, 
	"MAXPRODLOAD" FLOAT(126) DEFAULT 0, 
	"COLOR" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
