--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONSTEP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONSTEP" ADD CONSTRAINT "PRODSTEP_UOM_FK1" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONSTEP" ADD CONSTRAINT "PRODUCTIONSTEP_PRODFAMILY_FK" FOREIGN KEY ("PRODFAMILY")
	  REFERENCES "SCPOMGR"."PRODUCTIONFAMILY" ("PRODFAMILY") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONSTEP" ADD CONSTRAINT "PRODUCTIONSTEP_PRODMETHOD_FK1" FOREIGN KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
	  REFERENCES "SCPOMGR"."PRODUCTIONMETHOD" ("PRODUCTIONMETHOD", "ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONSTEP" ADD CONSTRAINT "PRODUCTIONSTEP_RES_FK1" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONSTEP" ADD CONSTRAINT "PRODUCTIONSTEP_SETUP_FK" FOREIGN KEY ("SETUP")
	  REFERENCES "SCPOMGR"."SETUP" ("SETUP") ENABLE
