--------------------------------------------------------
--  Ref Constraints for Table PRODUCTIONPENALTY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODUCTIONPENALTY" ADD CONSTRAINT "PRODPENALTY_PENALTYCAT_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCPOMGR"."PENALTYCATEGORY" ("CATEGORY") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONPENALTY" ADD CONSTRAINT "PRODPENALTY_PRODMETHOD_FK1" FOREIGN KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
	  REFERENCES "SCPOMGR"."PRODUCTIONMETHOD" ("PRODUCTIONMETHOD", "ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONPENALTY" ADD CONSTRAINT "PRODPENALTY_UOM_FK1" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONPENALTY" ADD CONSTRAINT "PRODPENALTY_UOM_FK2" FOREIGN KEY ("CURRENCYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."PRODUCTIONPENALTY" ADD CONSTRAINT "PRODUCTIONPENALTY_SKU_FK1" FOREIGN KEY ("OUTPUTITEM", "LOC")
	  REFERENCES "SCPOMGR"."SKU" ("ITEM", "LOC") ON DELETE CASCADE ENABLE
