--------------------------------------------------------
--  Ref Constraints for Table PRODRESPROJ
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."PRODRESPROJ" ADD CONSTRAINT "PRODRESPROJ_PRODMETHOD_FK1" FOREIGN KEY ("PRODUCTIONMETHOD", "ITEM", "LOC")
	  REFERENCES "SCPOMGR"."PRODUCTIONMETHOD" ("PRODUCTIONMETHOD", "ITEM", "LOC") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODRESPROJ" ADD CONSTRAINT "PRODRESPROJ_RES_FK1" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODRESPROJ" ADD CONSTRAINT "PRODRESPROJ_UOM_FK1" FOREIGN KEY ("NUMERATORUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODRESPROJ" ADD CONSTRAINT "PRODRESPROJ_UOM_FK2" FOREIGN KEY ("DENOMINATORUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."PRODRESPROJ" ADD CONSTRAINT "PRODRESPROJ_UOM_FK3" FOREIGN KEY ("ADDITIONALUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
