--------------------------------------------------------
--  DDL for Table PRODUCTIONSTEP
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."PRODUCTIONSTEP" 
   (	"STEPNUM" NUMBER(*,0) DEFAULT 0, 
	"NEXTSTEPTIMING" NUMBER(*,0) DEFAULT 3, 
	"FIXEDRESREQ" FLOAT(126) DEFAULT 0, 
	"PRODRATE" FLOAT(126) DEFAULT 0, 
	"PRODDUR" NUMBER(*,0) DEFAULT 0, 
	"PRODOFFSET" NUMBER(*,0) DEFAULT 0, 
	"ENABLESW" NUMBER(1,0) DEFAULT 1, 
	"SPREAD" NUMBER(*,0) DEFAULT 0, 
	"MAXSTARTDUR" NUMBER(*,0) DEFAULT 0, 
	"LOC" VARCHAR2(50 CHAR), 
	"ITEM" VARCHAR2(50 CHAR), 
	"RES" VARCHAR2(101 CHAR) DEFAULT ' ', 
	"PRODUCTIONMETHOD" VARCHAR2(50 CHAR), 
	"EFF" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"DESCR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"LOADOFFSETDUR" NUMBER(*,0) DEFAULT 0, 
	"PRODCOST" FLOAT(126) DEFAULT 0, 
	"QTYUOM" NUMBER(*,0) DEFAULT 0, 
	"SETUP" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"INUSEBEFORESW" NUMBER(1,0) DEFAULT 0, 
	"PRODFAMILY" VARCHAR2(50 CHAR) DEFAULT ' '
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONSTEP"."STEPNUM" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONSTEP"."SPREAD" IS 'The numbers of days over which the load on work center should be distributed.'
   COMMENT ON COLUMN "SCPOMGR"."PRODUCTIONSTEP"."SETUP" IS 'name of the Setup'
   COMMENT ON TABLE "SCPOMGR"."PRODUCTIONSTEP"  IS 'The ProductionRequirement table defines the resource requirements for a given production method.'
