--------------------------------------------------------
--  DDL for Table RES
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RES" 
   (	"SOURCE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"LOC" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"TYPE" NUMBER DEFAULT 4, 
	"RES" VARCHAR2(101 CHAR), 
	"DESCR" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"ENABLESW" NUMBER(1,0) DEFAULT 1, 
	"ADJFACTOR" FLOAT(126) DEFAULT 1, 
	"CHECKMAXCAP" NUMBER(*,0) DEFAULT 1, 
	"SUBTYPE" NUMBER(*,0) DEFAULT 0, 
	"QTYUOM" NUMBER(*,0) DEFAULT 0, 
	"CURRENCYUOM" NUMBER(*,0) DEFAULT 0, 
	"CAL" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"AVGFAMILYCHG" FLOAT(126) DEFAULT 0, 
	"AVGSKUCHG" FLOAT(126) DEFAULT 0, 
	"AVGSKUCHGCOST" FLOAT(126) DEFAULT 0, 
	"AVGFAMILYCHGCOST" FLOAT(126) DEFAULT 0, 
	"COST" FLOAT(126) DEFAULT 0, 
	"LEVELLOADSW" NUMBER(1,0) DEFAULT 0, 
	"LEVELSEQNUM" NUMBER(*,0) DEFAULT 1, 
	"CRITICALITEM" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"UNITPENALTY" FLOAT(126) DEFAULT 0, 
	"PRODUCTIONFAMILYCHGOVEROPT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 
  PARALLEL 8 

   COMMENT ON COLUMN "SCPOMGR"."RES"."SOURCE" IS 'Must contain a special location called "ANY" to support location independent BOMs.'
   COMMENT ON COLUMN "SCPOMGR"."RES"."LOC" IS 'Must contain a special location called "ANY" to support location independent BOMs.'
   COMMENT ON COLUMN "SCPOMGR"."RES"."CAL" IS 'Unique identifier / name for the calendar'
