--------------------------------------------------------
--  Constraints for Table RES
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_PK" PRIMARY KEY ("RES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "PRODUCTIONFAMILYCHGOVEROPT_CHK" CHECK (PRODUCTIONFAMILYCHGOVEROPT IN (0,1,2,3)) ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "BOOL_RES_LEVELLOADSW" CHECK (LEVELLOADSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_CHECKMAXCAP_CHK" CHECK (CHECKMAXCAP IN (1,2,3)) ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "BOOL_RES_ENABLESW" CHECK (EnableSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RESTYPE" CHECK (TYPE IN (4, 5, 6, 7, 8, 9)) ENABLE
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("UNITPENALTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("CRITICALITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("LEVELSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("LEVELLOADSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("COST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("AVGFAMILYCHGCOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("AVGSKUCHGCOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("AVGSKUCHG" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("AVGFAMILYCHG" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("CAL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("SUBTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("CHECKMAXCAP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("ADJFACTOR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("ENABLESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("DESCR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RES" MODIFY ("SOURCE" NOT NULL ENABLE)
