--------------------------------------------------------
--  Ref Constraints for Table RES
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_CAL_FK1" FOREIGN KEY ("CAL")
	  REFERENCES "SCPOMGR"."CAL" ("CAL") ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_ITEM_FK1" FOREIGN KEY ("CRITICALITEM")
	  REFERENCES "SCPOMGR"."ITEM" ("ITEM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_LOC_FK1" FOREIGN KEY ("LOC")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_LOC_FK2" FOREIGN KEY ("SOURCE")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_RESSUBTYPE_FK1" FOREIGN KEY ("SUBTYPE")
	  REFERENCES "SCPOMGR"."RESSUBTYPE" ("SUBTYPE") ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_UOM_FK2" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."RES" ADD CONSTRAINT "RES_UOM_FK3" FOREIGN KEY ("CURRENCYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
