--------------------------------------------------------
--  DDL for Table RESCOST
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RESCOST" 
   (	"CATEGORY" NUMBER(*,0), 
	"RES" VARCHAR2(101 CHAR), 
	"LOCALCOST" VARCHAR2(110 CHAR), 
	"TIEREDCOST" VARCHAR2(110 CHAR) DEFAULT ' '
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 
  PARALLEL 8 

   COMMENT ON COLUMN "SCPOMGR"."RESCOST"."CATEGORY" IS ' '
   COMMENT ON TABLE "SCPOMGR"."RESCOST"  IS 'Defines the time-phase costs associated with each resource.'
