--------------------------------------------------------
--  Ref Constraints for Table RESCONSTRAINT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESCONSTRAINT" ADD CONSTRAINT "RESCONSTRAINT_RES_FK1" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."RESCONSTRAINT" ADD CONSTRAINT "RESCONSTRAINT_UOM_FK1" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."RESCONSTRAINT" ADD CONSTRAINT "RESCONST_CONSTRCATEGORY_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCPOMGR"."CONSTRAINTCATEGORY" ("CATEGORY") ENABLE
  ALTER TABLE "SCPOMGR"."RESCONSTRAINT" ADD CONSTRAINT "RESCONTRAINT_TIMEUOM_FK" FOREIGN KEY ("TIMEUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
