--------------------------------------------------------
--  Ref Constraints for Table RESCOST
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESCOST" ADD CONSTRAINT "RESCOST_COSTCATEGORY_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCPOMGR"."COSTCATEGORY" ("CATEGORY") ENABLE
  ALTER TABLE "SCPOMGR"."RESCOST" ADD CONSTRAINT "RESCOST_COST_FK1" FOREIGN KEY ("LOCALCOST")
	  REFERENCES "SCPOMGR"."COST" ("COST") ENABLE
  ALTER TABLE "SCPOMGR"."RESCOST" ADD CONSTRAINT "RESCOST_COST_FK2" FOREIGN KEY ("TIEREDCOST")
	  REFERENCES "SCPOMGR"."COST" ("COST") ENABLE
  ALTER TABLE "SCPOMGR"."RESCOST" ADD CONSTRAINT "RESCOST_RES_FK1" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ON DELETE CASCADE ENABLE
