--------------------------------------------------------
--  Ref Constraints for Table RESEXCEPTION
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESEXCEPTION" ADD CONSTRAINT "RESEXCEPTION_PRODFAMILY_FK" FOREIGN KEY ("PRODFAMILY")
	  REFERENCES "SCPOMGR"."PRODUCTIONFAMILY" ("PRODFAMILY") ENABLE
  ALTER TABLE "SCPOMGR"."RESEXCEPTION" ADD CONSTRAINT "RESEXCEPTION_RES_FK1" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ENABLE
