--------------------------------------------------------
--  DDL for Table RESEXCEPTION
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RESEXCEPTION" 
   (	"SEQNUM" NUMBER(*,0), 
	"BATCHNUM" NUMBER(*,0) DEFAULT 0, 
	"PROCESSID" NUMBER(*,0) DEFAULT 0, 
	"SOURCE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"EXCEPTION" NUMBER(*,0), 
	"EXCEPTIONDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"PRODUCTIONMETHOD" VARCHAR2(50 CHAR), 
	"FUNCTIONNUM" NUMBER(*,0), 
	"WHEN" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"DESCR" VARCHAR2(1024 CHAR) DEFAULT ' ', 
	"USERID" VARCHAR2(256 CHAR) DEFAULT ' ', 
	"FUNCTIONNAME" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"LOADQTY" FLOAT(126) DEFAULT 0, 
	"SUPPLYQTY" FLOAT(126) DEFAULT 0, 
	"RES" VARCHAR2(101 CHAR), 
	"SOURCING" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"STEPNUM" NUMBER(*,0) DEFAULT 0, 
	"LOC" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"ITEM" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"PRODFAMILY" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"REVIEWEDSTATUS" NUMBER(*,0) DEFAULT 1, 
	"CATEGORY" NUMBER(*,0) DEFAULT 0, 
	"SEVERITY" NUMBER(*,0) DEFAULT 0, 
	"LASTUPDATEDON" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"LASTUPDATEDBY" VARCHAR2(256 CHAR) DEFAULT ' '
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."RESEXCEPTION"."PRODUCTIONMETHOD" IS 'Associate Production Method'
   COMMENT ON COLUMN "SCPOMGR"."RESEXCEPTION"."DESCR" IS 'Text Decription of Exception'
