--------------------------------------------------------
--  DDL for Index RESLOADREQUIREMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."RESLOADREQUIREMENT_PK" ON "SCPOMGR"."RESLOADREQUIREMENT" ("ITEM", "LOC", "RES", "PRODUCTIONMETHOD", "STEPNUM", "WHENLOADED", "SUPPLYSEQNUM", "SUPPLYTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"
