--------------------------------------------------------
--  DDL for Table RESLOADDETAIL
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RESLOADDETAIL" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"RES" VARCHAR2(150 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"SUPPLYTYPE" NUMBER, 
	"PRODUCTIONMETHOD" VARCHAR2(50 CHAR), 
	"STEPNUM" NUMBER, 
	"WHENLOADED" DATE, 
	"LOADQTY" FLOAT(126) DEFAULT 0, 
	"SOURCEOPT" NUMBER DEFAULT 1, 
	"RESLOC" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"CUSTORDLOADQTY" FLOAT(126) DEFAULT 0.0, 
	"FCSTORDLOADQTY" FLOAT(126) DEFAULT 0.0, 
	"SSLOADQTY" FLOAT(126) DEFAULT 0, 
	"SUPPLYQTY" FLOAT(126) DEFAULT 0, 
	"STARTDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SUPPLYSEQNUM" NUMBER(*,0), 
	"SOURCE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"NEEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"SCHEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"EXPDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"PROCESSID" NUMBER(*,0) DEFAULT 0, 
	"OFFSET" NUMBER(*,0) DEFAULT 0, 
	"ROUTINGNEEDCOMPLETEDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"DMDNEEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"DMDORDERSEQNUM" NUMBER DEFAULT -1, 
	"DMDORDERTYPE" NUMBER DEFAULT -1, 
	"SUPPLYORDERSEQNUM" NUMBER(*,0) DEFAULT -1, 
	"OPTIONSETNAME" VARCHAR2(255 CHAR) DEFAULT ' ', 
	"SUPPLYORDERNUM" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."RESLOADDETAIL"."PROCESSID" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESLOADDETAIL"."OFFSET" IS 'The difference between the Supply due date and the Load date.'
   COMMENT ON COLUMN "SCPOMGR"."RESLOADDETAIL"."ROUTINGNEEDCOMPLETEDATE" IS 'Last Day of Loading of step with all available capacity'
   COMMENT ON COLUMN "SCPOMGR"."RESLOADDETAIL"."DMDNEEDDATE" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESLOADDETAIL"."DMDORDERSEQNUM" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESLOADDETAIL"."DMDORDERTYPE" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESLOADDETAIL"."SUPPLYORDERSEQNUM" IS 'The seq number of supply order'
   COMMENT ON COLUMN "SCPOMGR"."RESLOADDETAIL"."OPTIONSETNAME" IS 'Reso or RRP option set name'
