--------------------------------------------------------
--  DDL for Table RESLOADREQUIREMENT
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RESLOADREQUIREMENT" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"RES" VARCHAR2(50 CHAR), 
	"PRODUCTIONMETHOD" VARCHAR2(50 CHAR), 
	"STEPNUM" NUMBER, 
	"WHENLOADED" DATE, 
	"SUPPLYSEQNUM" NUMBER(*,0), 
	"SUPPLYTYPE" NUMBER, 
	"LOADQTY" FLOAT(126) DEFAULT 0, 
	"SUPPLYQTY" FLOAT(126) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SCPODATA"
