--------------------------------------------------------
--  DDL for Index RESLOADDETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."RESLOADDETAIL_PK" ON "SCPOMGR"."RESLOADDETAIL" ("ITEM", "LOC", "RES", "SUPPLYTYPE", "PRODUCTIONMETHOD", "STEPNUM", "WHENLOADED", "PROCESSID", "SOURCE", "EXPDATE", "NEEDDATE", "SCHEDDATE", "SUPPLYSEQNUM", "STARTDATE", "DMDNEEDDATE", "DMDORDERSEQNUM", "DMDORDERTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
