--------------------------------------------------------
--  DDL for Table RESMETRIC
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RESMETRIC" 
   (	"EFF" DATE, 
	"VALUE" FLOAT(126), 
	"DUR" NUMBER(*,0), 
	"CATEGORY" NUMBER(*,0), 
	"RES" VARCHAR2(101 CHAR), 
	"CURRENCYUOM" NUMBER(*,0) DEFAULT 0, 
	"TIMEUOM" NUMBER(*,0) DEFAULT 0, 
	"QTYUOM" NUMBER(*,0) DEFAULT 0, 
	"SETUP" VARCHAR2(50 CHAR) DEFAULT ' '
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 
  PARALLEL 8 

   COMMENT ON COLUMN "SCPOMGR"."RESMETRIC"."CATEGORY" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESMETRIC"."SETUP" IS ' '
