--------------------------------------------------------
--  Ref Constraints for Table RESMETRIC
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESMETRIC" ADD CONSTRAINT "RESMETRIC_CURRUOM_FK" FOREIGN KEY ("CURRENCYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."RESMETRIC" ADD CONSTRAINT "RESMETRIC_METRICCATEGORY_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCPOMGR"."METRICCATEGORY" ("CATEGORY") ENABLE
  ALTER TABLE "SCPOMGR"."RESMETRIC" ADD CONSTRAINT "RESMETRIC_QTYUOM_FK" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."RESMETRIC" ADD CONSTRAINT "RESMETRIC_RES_FK1" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."RESMETRIC" ADD CONSTRAINT "RESMETRIC_SETUP_FK" FOREIGN KEY ("SETUP")
	  REFERENCES "SCPOMGR"."SETUP" ("SETUP") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."RESMETRIC" ADD CONSTRAINT "RESMETRIC_TIMEUOM_FK" FOREIGN KEY ("TIMEUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
