--------------------------------------------------------
--  DDL for Table RESOINDEPENDENTDMD
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RESOINDEPENDENTDMD" 
   (	"PROCESSID" NUMBER(*,0), 
	"DMDORDERTYPE" NUMBER(*,0), 
	"DMDORDERSEQNUM" NUMBER(*,0), 
	"STATUS" NUMBER(*,0) DEFAULT 1, 
	"COSTINVEST" FLOAT(126) DEFAULT 0, 
	"SCHEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"REVENUE" FLOAT(126) DEFAULT 0, 
	"MARGIN" FLOAT(126) DEFAULT 0, 
	"ORDERNUM" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"LINENUM" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"STDCOST" FLOAT(126) DEFAULT 0, 
	"POSSIBLEQTY" FLOAT(126) DEFAULT 0, 
	"ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"NEEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"DMDQTY" FLOAT(126) DEFAULT 0, 
	"PEGSETNUM" NUMBER(*,0) DEFAULT 0, 
	"PRIORITY" NUMBER(*,0) DEFAULT 0, 
	"CAPACITYSCHEDDATE" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"CAPACITYSTATUS" NUMBER(*,0) DEFAULT -1, 
	"OPTIONSETNAME" VARCHAR2(255 CHAR) DEFAULT ' '
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."PROCESSID" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."DMDORDERTYPE" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."DMDORDERSEQNUM" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."STATUS" IS 'On time, early, or late'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."COSTINVEST" IS 'Additional cost to fulfill the order'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."SCHEDDATE" IS 'Scheduled (available) date'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."REVENUE" IS 'Revenue from the order'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."MARGIN" IS 'Margin (profit) from the order'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."ORDERNUM" IS 'Order identifier'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."LINENUM" IS 'Line (sub-order) identifier'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."STDCOST" IS 'Standard cost of the need quantity'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."POSSIBLEQTY" IS 'How much of the need quantity is available on the need date (may not exceed need quantity).'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."LOC" IS 'Must contain a special location called "ANY" to support location independent BOMs.'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."NEEDDATE" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."DMDQTY" IS 'Required quantity'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."PEGSETNUM" IS 'Used by RESO for sorting the independent demands within a priority'''
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."PRIORITY" IS 'Priority Used by RESO when processing the independent demands'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."CAPACITYSCHEDDATE" IS 'Capacity Available Date'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."CAPACITYSTATUS" IS 'Status of order considering capacity'
   COMMENT ON COLUMN "SCPOMGR"."RESOINDEPENDENTDMD"."OPTIONSETNAME" IS 'Reso option set name'
   COMMENT ON TABLE "SCPOMGR"."RESOINDEPENDENTDMD"  IS 'RESO output; equivalent to updated version of ResoIn'
