--------------------------------------------------------
--  Constraints for Table RESOSUPPLYDETAIL
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" ADD CONSTRAINT "XPKRESOSUPPLYDETAIL" PRIMARY KEY ("PROCESSID", "DMDORDERTYPE", "DMDORDERSEQNUM", "DMDNEEDDATE", "SUPPLYSEQNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" ADD CONSTRAINT "SUPPLYACTIONS" CHECK (SupplyAction IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)) ENABLE
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" ADD CONSTRAINT "RESOSPLYDET_DMDORDTYPE" CHECK (DmdOrderType IN (-103, -105, -110, -115, -120, -125, -130, -135, -140, -150, 0)) ENABLE
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" ADD CONSTRAINT "SUPPLYSUPPLYORDER" CHECK (SupplyOrderType IN (105, 110, 115, 120, 125, 130, 135, 140, 145)) ENABLE
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("OPTIONSETNAME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("LINENUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("ORDERNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("CAPACITYSCHEDDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SUBSTITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SUPPLYACTION" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("ORDERCOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("USEDCOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("NEEDCOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("DMDNEEDDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SUPPLYORDERSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("DMDORDERTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SUBSTLOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("POSSIBLEQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SCRAPQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("PROJECTID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("PLANLEVEL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SUPPLYORDERTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("DMDQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("NEEDDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SCHEDDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SUPPLYQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("LEADTIME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("SUPPLYSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("DMDORDERSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" MODIFY ("PROCESSID" NOT NULL ENABLE)
