--------------------------------------------------------
--  Constraints for Table RESOIN
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESOIN" ADD CONSTRAINT "XPKRESOIN" PRIMARY KEY ("PROCESSID", "DMDORDERTYPE", "DMDORDERSEQNUM", "NEEDDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."RESOIN" ADD CONSTRAINT "SUBSTITUTIONOPERATORS3" CHECK (SubstOperator IN (1, 2, 3, 4, 5, 6, 0)) ENABLE
  ALTER TABLE "SCPOMGR"."RESOIN" ADD CONSTRAINT "SUPPLYDEMANDORDERTYPES" CHECK (DmdOrderType IN (-103, -105, -110, -115, -120, -125, -130, -135, -140, -150, 0)) ENABLE
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("OPTIONSETNAME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("PEGSETNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("LINENUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("ORDERNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("REVENUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("PRIORITY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("DMDQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("NEEDDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("SUBSTOPERATOR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("SUBSTLEVEL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("PROJECTID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("STDCOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("DMDORDERSEQNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("DMDORDERTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."RESOIN" MODIFY ("PROCESSID" NOT NULL ENABLE)
