--------------------------------------------------------
--  Ref Constraints for Table RESOSUPPLYDETAIL
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" ADD CONSTRAINT "RESOSUPPLYDETAIL_LOC_FK1" FOREIGN KEY ("SUBSTLOC")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") ENABLE
  ALTER TABLE "SCPOMGR"."RESOSUPPLYDETAIL" ADD CONSTRAINT "RESOSUPPLYDETAIL_SKU_FK1" FOREIGN KEY ("ITEM", "LOC")
	  REFERENCES "SCPOMGR"."SKU" ("ITEM", "LOC") ON DELETE CASCADE ENABLE
