--------------------------------------------------------
--  Ref Constraints for Table RESPROJ
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESPROJ" ADD CONSTRAINT "RESPROJ_RES_FK1" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."RESPROJ" ADD CONSTRAINT "RESPROJ_RES_FK3" FOREIGN KEY ("ADDITIONALUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."RESPROJ" ADD CONSTRAINT "RESPROJ_UOM_FK1" FOREIGN KEY ("NUMERATORUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."RESPROJ" ADD CONSTRAINT "RESPROJ_UOM_FK2" FOREIGN KEY ("DENOMINATORUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ON DELETE CASCADE ENABLE
