--------------------------------------------------------
--  DDL for Table RESPROJ
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RESPROJ" 
   (	"RES" VARCHAR2(101 CHAR) DEFAULT ' ', 
	"TVQCATEGORY" NUMBER(*,0) DEFAULT -1, 
	"NUMERATORUOM" NUMBER(*,0) DEFAULT 0, 
	"EFF" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"DENOMINATORUOM" NUMBER(*,0) DEFAULT 0, 
	"ADDITIONALUOM" NUMBER(*,0) DEFAULT 0, 
	"OPTIONSETNAME" VARCHAR2(255 CHAR) DEFAULT ' ', 
	"POLICY" NUMBER(*,0) DEFAULT 0, 
	"VALUE" FLOAT(126) DEFAULT 0, 
	"DUR" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SCPODATA"
