--------------------------------------------------------
--  Ref Constraints for Table RESPENALTY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."RESPENALTY" ADD CONSTRAINT "RESPENALTY_PENALTYCAT_FK1" FOREIGN KEY ("CATEGORY")
	  REFERENCES "SCPOMGR"."PENALTYCATEGORY" ("CATEGORY") ENABLE
  ALTER TABLE "SCPOMGR"."RESPENALTY" ADD CONSTRAINT "RESPENALTY_RES_FK1" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."RES" ("RES") ON DELETE CASCADE ENABLE
  ALTER TABLE "SCPOMGR"."RESPENALTY" ADD CONSTRAINT "RESPENALTY_TIMEUOM_FK" FOREIGN KEY ("TIMEUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."RESPENALTY" ADD CONSTRAINT "RESPENALTY_UOM_FK1" FOREIGN KEY ("QTYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
  ALTER TABLE "SCPOMGR"."RESPENALTY" ADD CONSTRAINT "RESPENALTY_UOM_FK2" FOREIGN KEY ("CURRENCYUOM")
	  REFERENCES "SCPOMGR"."UOM" ("UOM") ENABLE
