--------------------------------------------------------
--  DDL for Table RESSUBTYPE_TRANS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."RESSUBTYPE_TRANS" 
   (	"SUBTYPE" NUMBER(*,0), 
	"COUNTRY_CODE" VARCHAR2(20 CHAR), 
	"LANGUAGE_CODE" VARCHAR2(20 CHAR), 
	"LABEL" VARCHAR2(256 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
