--------------------------------------------------------
--  DDL for Table SKU
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."SKU" 
   (	"ITEM" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"OH" FLOAT(126) DEFAULT 0, 
	"SOURCINGGROUP" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"REPLENTYPE" NUMBER DEFAULT 1, 
	"NETCHGSW" NUMBER(1,0) DEFAULT 1, 
	"OHPOST" DATE DEFAULT TO_DATE('01/01/1970','MM/DD/YYYY'), 
	"PLANLEVEL" NUMBER(38,0) DEFAULT -1, 
	"QTYUOM" NUMBER(*,0) DEFAULT 0, 
	"CURRENCYUOM" NUMBER(*,0) DEFAULT 0, 
	"STORABLESW" NUMBER(1,0) DEFAULT 1, 
	"ENABLESW" NUMBER(1,0) DEFAULT 1, 
	"TIMEUOM" NUMBER(*,0) DEFAULT 35, 
	"FF_TRIGGER_CONTROL" NUMBER(*,0), 
	"INFCARRYFWDSW" NUMBER(1,0) DEFAULT 0, 
	"MINOHCOVRULE" NUMBER(*,0) DEFAULT 1, 
	"LTDGROUP" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"TARGETOHCOVRULE" NUMBER(*,0) DEFAULT 1, 
	"INFINITESUPPLYSW" NUMBER(1,0) DEFAULT 0, 
	"SEQINTENABLESW" NUMBER(1,0) DEFAULT 0, 
	"MPBATCHNUM" NUMBER(*,0) DEFAULT 0, 
	"ITEMSTOREGRADE" NUMBER(*,0) DEFAULT -1, 
	"RPBATCHNUM" NUMBER(*,0) DEFAULT 0, 
	"U_NEW" NUMBER(1,0), 
	"U_DELETE" NUMBER(1,0) DEFAULT 0, 
	"U_DL_TIME" DATE DEFAULT TO_DATE('01/01/1970', 'MM/dd/yyyy')
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" 

   COMMENT ON COLUMN "SCPOMGR"."SKU"."LOC" IS ' '
   COMMENT ON COLUMN "SCPOMGR"."SKU"."ITEMSTOREGRADE" IS 'Grade of the Store based on Average Sales of an Item'
