--------------------------------------------------------
--  Constraints for Table SKU
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("ITEMSTOREGRADE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("U_DELETE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "SKU_PK" PRIMARY KEY ("ITEM", "LOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "CHK_SKU_MPBATCHNUM" CHECK (MPBatchNum >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "BOOL_SKU_INFINITESUPPLYSW" CHECK (InfiniteSupplySw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "ONHANDCOVERAGERULES2" CHECK (TargetOHCovRule IN (1, 2)) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "ONHANDCOVERAGERULES" CHECK (MinOHCovRule IN (1, 2)) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "BOOL_SKU_INFCARRYFWDSW" CHECK (InfCarryFwdSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "BOOL_SKU_ENABLESW" CHECK (EnableSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "BOOL_SKU_STORABLESW" CHECK (StorableSw IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "BOOL_SKU_NETCHGSW" CHECK (NETCHGSW IN (0, 1)) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" ADD CONSTRAINT "SKU_REPLEN_TYPES" CHECK (REPLENTYPE IN (1, 2, 3, 4, 5, 6)) ENABLE
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("MPBATCHNUM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("SEQINTENABLESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("INFINITESUPPLYSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("TARGETOHCOVRULE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("LTDGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("MINOHCOVRULE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("INFCARRYFWDSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("TIMEUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("ENABLESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("STORABLESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("PLANLEVEL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("OHPOST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("NETCHGSW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("REPLENTYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("SOURCINGGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("OH" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."SKU" MODIFY ("ITEM" NOT NULL ENABLE)
