--------------------------------------------------------
--  File created - Tuesday-September-08-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDT_YIELD
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_YIELD" 
   (	"LOC" VARCHAR2(4 CHAR), 
	"MATCODE" VARCHAR2(5 CHAR) DEFAULT 0, 
	"QB" VARCHAR2(14 CHAR) DEFAULT 0, 
	"ITEM" VARCHAR2(15 CHAR), 
	"PRODUCTIONMETHOD" VARCHAR2(3 CHAR), 
	"EFFICIENCY" NUMBER DEFAULT 1, 
	"MAXHRSPERDAY" NUMBER DEFAULT 0, 
	"MINHRSPERDAY" NUMBER DEFAULT 0, 
	"MAXDAYSPERWK" NUMBER DEFAULT 0, 
	"MINDAYSPERWK" NUMBER DEFAULT 0, 
	"MAXCAP" NUMBER DEFAULT 0, 
	"MINCAP" NUMBER DEFAULT 0, 
	"YIELD" NUMBER DEFAULT 0, 
	"DND" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_YIELD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_YIELD_PK" ON "SCPOMGR"."UDT_YIELD" ("LOC", "ITEM", "PRODUCTIONMETHOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table UDT_YIELD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_PK" PRIMARY KEY ("LOC", "ITEM", "PRODUCTIONMETHOD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_C03" CHECK (MINHRSPERDAY <= MAXHRSPERDAY AND MINDAYSPERWK <=MAXDAYSPERWK) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_C02" CHECK (MINCAP <= MAXCAP) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_C01" CHECK (DND IN (1, 0)) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CHECK (EFFICIENCY > 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("DND" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("YIELD" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MINCAP" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MAXCAP" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MINDAYSPERWK" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MAXDAYSPERWK" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MINHRSPERDAY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MAXHRSPERDAY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("EFFICIENCY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("QB" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MATCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table UDT_YIELD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_LOC_FK1" FOREIGN KEY ("LOC")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") ENABLE;
