--------------------------------------------------------
--  DDL for Table UDT_LOC_TYPE
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_LOC_TYPE" 
   (	"LOC_TYPE" NUMBER(38,0) DEFAULT 6, 
	"DESCRIPTION" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
