--------------------------------------------------------
--  Constraints for Table UDT_SKUMETRIC_ALT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_ALT" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_ALT" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_ALT" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_ALT" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_ALT" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_ALT" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_ALT" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_ALT" MODIFY ("EFF" NOT NULL ENABLE)
