--------------------------------------------------------
--  Constraints for Table UDT_SOURCINGRESMETRIC_RB
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_RB" MODIFY ("SOURCING" NOT NULL ENABLE)
