--------------------------------------------------------
--  DDL for Table UDT_COST_TRANSIT_BKP_28AUG15
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" 
   (	"DIRECTION" VARCHAR2(2 CHAR), 
	"SOURCE_CO" VARCHAR2(2 CHAR), 
	"SOURCE_PC" VARCHAR2(8 CHAR), 
	"DEST_CO" VARCHAR2(2 CHAR), 
	"DEST_PC" VARCHAR2(8 CHAR), 
	"SALESGROUP" VARCHAR2(8 CHAR), 
	"TRANSITTIME" NUMBER, 
	"COST_KM" NUMBER, 
	"COST_PALLET" NUMBER, 
	"DISTANCE" NUMBER(24,6), 
	"SOURCE_GEO" VARCHAR2(3 CHAR), 
	"DEST_GEO" VARCHAR2(3 CHAR), 
	"U_RATE_TYPE" VARCHAR2(1 CHAR), 
	"U_EQUIPMENT_TYPE" VARCHAR2(50), 
	"LANE_TYPE" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
