--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDT_COST_UNIT
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_COST_UNIT" 
   (	"LOC" VARCHAR2(50 CHAR), 
	"COMPANY" VARCHAR2(4 CHAR) DEFAULT ' ', 
	"MATCODE" VARCHAR2(5 CHAR), 
	"PROCESS" VARCHAR2(15 CHAR), 
	"UNIT_COST" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_COST_UNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_COST_UNIT_PK" ON "SCPOMGR"."UDT_COST_UNIT" ("LOC", "MATCODE", "PROCESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table UDT_COST_UNIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" ADD CONSTRAINT "UDT_COST_UNIT_PK" PRIMARY KEY ("LOC", "MATCODE", "PROCESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" ADD CONSTRAINT "UDT_COST_UNIT_C01" CHECK (UNIT_COST >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("UNIT_COST" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("LOC" NOT NULL ENABLE);
