--------------------------------------------------------
--  Constraints for Table UDT_ACTIVE_SITES_TEMP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_ACTIVE_SITES_TEMP" ADD CONSTRAINT "UDT_ACTIVE_SITES_PK" PRIMARY KEY ("LOC", "RES")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_ACTIVE_SITES_TEMP" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_ACTIVE_SITES_TEMP" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_ACTIVE_SITES_TEMP" MODIFY ("LOC" NOT NULL ENABLE)
