--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDT_RATE_TYPE
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_RATE_TYPE" 
   (	"U_RATE_TYPE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_RATE_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_RATE_TYPE_PK" ON "SCPOMGR"."UDT_RATE_TYPE" ("U_RATE_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table UDT_RATE_TYPE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_RATE_TYPE" ADD CONSTRAINT "UDT_RATE_TYPE_PK" PRIMARY KEY ("U_RATE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_RATE_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_RATE_TYPE" MODIFY ("U_RATE_TYPE" NOT NULL ENABLE);
