--------------------------------------------------------
--  DDL for Table UDT_YIELD
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_YIELD" 
   (	"LOC" VARCHAR2(4 CHAR), 
	"MATCODE" VARCHAR2(5 CHAR) DEFAULT 0, 
	"QB" VARCHAR2(14 CHAR) DEFAULT 0, 
	"ITEM" VARCHAR2(15 CHAR), 
	"PRODUCTIONMETHOD" VARCHAR2(3 CHAR), 
	"EFFICIENCY" NUMBER DEFAULT 1, 
	"MAXHRSPERDAY" NUMBER DEFAULT 0, 
	"MINHRSPERDAY" NUMBER DEFAULT 0, 
	"MAXDAYSPERWK" NUMBER DEFAULT 0, 
	"MINDAYSPERWK" NUMBER DEFAULT 0, 
	"MAXCAP" NUMBER DEFAULT 0, 
	"MINCAP" NUMBER DEFAULT 0, 
	"YIELD" NUMBER DEFAULT 0, 
	"DND" NUMBER(*,0) DEFAULT 0
   )
