--------------------------------------------------------
--  Constraints for Table UDT_EQUIPMENT_CONVERSION
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("EQUIPMENT_NATIVE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("U_AREA" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ADD CONSTRAINT "UDT_EQUIPMENT_CONVERSION_PK" PRIMARY KEY ("COMPANYID", "U_AREA", "EQUIPMENT_NATIVE", "U_EQUIPMENT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
