--------------------------------------------------------
--  Constraints for Table UDT_IGPERROR_STATS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_IGPERROR_STATS" ADD CONSTRAINT "UDT_IGPERROR_STATS_PK" PRIMARY KEY ("RUN_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_IGPERROR_STATS" MODIFY ("RUN_DATE" NOT NULL ENABLE)
