--------------------------------------------------------
--  DDL for Table UDT_INTJOBS_HISTORY
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_INTJOBS_HISTORY" 
   (	"JOBID" VARCHAR2(32 CHAR), 
	"INT_TABLENAME" VARCHAR2(30 CHAR), 
	"TABLENAME" VARCHAR2(30 CHAR), 
	"INSERTCT" NUMBER(*,0), 
	"UPDATECT" NUMBER(*,0), 
	"TOTALROWSCT" NUMBER(*,0), 
	"LASTEXEC" VARCHAR2(17), 
	"ERRORCODE" VARCHAR2(9 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
