--------------------------------------------------------
--  Constraints for Table UDT_SKUMETRIC_RB
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_RB" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_RB" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_RB" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_RB" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_RB" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_RB" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_RB" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_RB" MODIFY ("EFF" NOT NULL ENABLE)
