--------------------------------------------------------
--  Constraints for Table UDT_DEFAULT_ZIP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_DEFAULT_ZIP" ADD CONSTRAINT "PK_UDT_DEFAULT_ZIP" PRIMARY KEY ("POSTALCODE", "LOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_DEFAULT_ZIP" MODIFY ("LOC" NOT NULL ENABLE);
