--------------------------------------------------------
--  DDL for Table UDT_YIELD_TMP
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_YIELD_TMP" 
   (	"LOC" VARCHAR2(4 CHAR), 
	"MATCODE" VARCHAR2(5 CHAR), 
	"QB" VARCHAR2(14 CHAR), 
	"ITEM" VARCHAR2(15 CHAR), 
	"PRODUCTIONMETHOD" VARCHAR2(3 CHAR), 
	"EFFICIENCY" NUMBER, 
	"MAXHRSPERDAY" NUMBER, 
	"MINHRSPERDAY" NUMBER, 
	"MAXDAYSPERWK" NUMBER, 
	"MINDAYSPERWK" NUMBER, 
	"MAXCAP" NUMBER, 
	"MINCAP" NUMBER, 
	"YIELD" NUMBER, 
	"DND" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
