--------------------------------------------------------
--  Constraints for Table UDT_FCST_WK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("MARKETMGRVERSIONID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("LEWMEANQTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("MODEL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("QTY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("FCSTID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("STARTDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("DMDGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FCST_WK" MODIFY ("DMDUNIT" NOT NULL ENABLE)
