--------------------------------------------------------
--  Constraints for Table UDT_LLAMASOFT_DATA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" ADD CONSTRAINT "UDT_LAMMASOFT_DATA_PK" PRIMARY KEY ("ITEM", "SOURCE", "DEST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" MODIFY ("DEST" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_LLAMASOFT_DATA" MODIFY ("ITEM" NOT NULL ENABLE);
