--------------------------------------------------------
--  DDL for Table UDT_PLANT_STATUS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_PLANT_STATUS" 
   (	"LOC" VARCHAR2(30 CHAR), 
	"U_MATERIALCODE" VARCHAR2(30 CHAR), 
	"U_STOCK" VARCHAR2(30 CHAR), 
	"RES" VARCHAR2(30 CHAR), 
	"STATUS" VARCHAR2(30 CHAR), 
	"U_EQUIPMENT_TYPE" VARCHAR2(50) DEFAULT ' '
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
