--------------------------------------------------------
--  Ref Constraints for Table UDT_COST_TRANSIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_DIR_FK1" FOREIGN KEY ("DIRECTION")
	  REFERENCES "SCPOMGR"."UDT_DIRECTION" ("U_DIRECTION") ENABLE
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_EQP_FK2" FOREIGN KEY ("U_EQUIPMENT_TYPE")
	  REFERENCES "SCPOMGR"."UDT_EQUIPMENT_TYPE" ("U_EQUIPMENT_TYPE") ENABLE
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_LANE__FK4" FOREIGN KEY ("LANE_TYPE")
	  REFERENCES "SCPOMGR"."UDT_LANE_TYPE" ("LANE_TYPE") ENABLE
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_RATE_FK3" FOREIGN KEY ("U_RATE_TYPE")
	  REFERENCES "SCPOMGR"."UDT_RATE_TYPE" ("U_RATE_TYPE") ENABLE
