--------------------------------------------------------
--  Constraints for Table UDT_PRODUCTIONRESMETRIC_ALT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_ALT" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
