--------------------------------------------------------
--  DDL for Table UDT_SOURCING_DEFINITIONS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_SOURCING_DEFINITIONS" 
   (	"SOURCING" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(150), 
	"CREATED_IN" VARCHAR2(50), 
	"ZIP_TYPE" VARCHAR2(20), 
	"SOURCING_TYPE" VARCHAR2(20), 
	"RES" VARCHAR2(101)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
