--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDT_DIRECTION
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_DIRECTION" 
   (	"U_DIRECTION" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_DIRECTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_DIRECTION_PK" ON "SCPOMGR"."UDT_DIRECTION" ("U_DIRECTION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table UDT_DIRECTION
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_DIRECTION" ADD CONSTRAINT "UDT_DIRECTION_PK" PRIMARY KEY ("U_DIRECTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_DIRECTION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_DIRECTION" MODIFY ("U_DIRECTION" NOT NULL ENABLE);
