--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDT_COST_TRANSIT
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_COST_TRANSIT" 
   (	"DIRECTION" VARCHAR2(2 CHAR) DEFAULT ' ', 
	"SOURCE_CO" VARCHAR2(2 CHAR) DEFAULT ' ', 
	"SOURCE_PC" VARCHAR2(8 CHAR) DEFAULT ' ', 
	"DEST_CO" VARCHAR2(2 CHAR) DEFAULT ' ', 
	"DEST_PC" VARCHAR2(8 CHAR) DEFAULT ' ', 
	"SALESGROUP" VARCHAR2(8 CHAR) DEFAULT ' ', 
	"TRANSITTIME" NUMBER DEFAULT 0, 
	"COST_KM" NUMBER DEFAULT 0, 
	"COST_PALLET" NUMBER DEFAULT 0, 
	"DISTANCE" NUMBER(24,6) DEFAULT 0, 
	"SOURCE_GEO" VARCHAR2(3 CHAR) DEFAULT ' ', 
	"DEST_GEO" VARCHAR2(3 CHAR) DEFAULT ' ', 
	"U_RATE_TYPE" VARCHAR2(1 CHAR) DEFAULT 'U', 
	"U_EQUIPMENT_TYPE" VARCHAR2(50 BYTE) DEFAULT ' ', 
	"LANE_TYPE" VARCHAR2(50 BYTE) DEFAULT ' '
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;

   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."DIRECTION" IS 'Transaction flow type (Issue vs Collection...)';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."SOURCE_CO" IS 'Country of the source location';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."SOURCE_PC" IS 'postal code of the source location';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."DEST_CO" IS 'Cuountry of the destinaitn location.';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."DEST_PC" IS 'Postal code of the destination locaiton.';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."COST_KM" IS 'Cost in miles for US and Km for EU';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."COST_PALLET" IS 'Cost per pallet in dollars';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."DISTANCE" IS 'distinace in miles or kilometers';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."SOURCE_GEO" IS 'Source GeoCode - First thres digits of the 5 digit postal code.';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."DEST_GEO" IS 'Destination GeoCode - First thres digits of the 5 digit postal code.';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."U_RATE_TYPE" IS 'Rate type: Spot or Other';
   COMMENT ON COLUMN "SCPOMGR"."UDT_COST_TRANSIT"."U_EQUIPMENT_TYPE" IS 'Used to hold the equipment type of Flatbed or Tailer.';
--------------------------------------------------------
--  DDL for Index UDT_COST_TRANIST_NEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_COST_TRANIST_NEW_PK" ON "SCPOMGR"."UDT_COST_TRANSIT" ("DIRECTION", "U_EQUIPMENT_TYPE", "SOURCE_PC", "DEST_PC", "SOURCE_GEO", "DEST_GEO", "SOURCE_CO", "DEST_CO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_COST_TRANSIT_IDX3
--------------------------------------------------------

  CREATE INDEX "SCPOMGR"."UDT_COST_TRANSIT_IDX3" ON "SCPOMGR"."UDT_COST_TRANSIT" ("DEST_PC", "SOURCE_PC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_COST_TRANIST_GEO_IDX2
--------------------------------------------------------

  CREATE INDEX "SCPOMGR"."UDT_COST_TRANIST_GEO_IDX2" ON "SCPOMGR"."UDT_COST_TRANSIT" ("DIRECTION", "U_EQUIPMENT_TYPE", "DEST_GEO", "SOURCE_GEO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_COST_TRANIST_PC_IDX1
--------------------------------------------------------

  CREATE INDEX "SCPOMGR"."UDT_COST_TRANIST_PC_IDX1" ON "SCPOMGR"."UDT_COST_TRANSIT" ("DIRECTION", "U_EQUIPMENT_TYPE", "DEST_PC", "SOURCE_PC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table UDT_COST_TRANSIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANIST_NEW_PK" PRIMARY KEY ("DIRECTION", "U_EQUIPMENT_TYPE", "SOURCE_PC", "DEST_PC", "SOURCE_GEO", "DEST_GEO", "SOURCE_CO", "DEST_CO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_SPC_CHK1" CHECK ((TRIM(SOURCE_PC) IS NOT NULL AND TRIM(SOURCE_GEO) IS NULL) OR (TRIM(SOURCE_PC) IS NULL AND TRIM(SOURCE_GEO) IS NOT NULL)) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_DPC_CHK1" CHECK ((TRIM(DEST_PC) IS NOT NULL AND TRIM(DEST_GEO) IS NULL) OR (TRIM(DEST_PC) IS NULL AND TRIM(DEST_GEO) IS NOT NULL)) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANIST_TRTM_CHK2" CHECK (TRANSITTIME >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANIST_PAL_CHK3" CHECK (COST_PALLET >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANIST_COST_CHK4" CHECK (COST_KM >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("LANE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DEST_GEO" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("SOURCE_GEO" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DISTANCE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("COST_PALLET" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("COST_KM" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("TRANSITTIME" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("SALESGROUP" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DEST_PC" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DEST_CO" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("SOURCE_PC" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("SOURCE_CO" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DIRECTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table UDT_COST_TRANSIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_DIR_FK1" FOREIGN KEY ("DIRECTION")
	  REFERENCES "SCPOMGR"."UDT_DIRECTION" ("U_DIRECTION") ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_EQP_FK2" FOREIGN KEY ("U_EQUIPMENT_TYPE")
	  REFERENCES "SCPOMGR"."UDT_EQUIPMENT_TYPE" ("U_EQUIPMENT_TYPE") ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_LANE__FK4" FOREIGN KEY ("LANE_TYPE")
	  REFERENCES "SCPOMGR"."UDT_LANE_TYPE" ("LANE_TYPE") ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_RATE_FK3" FOREIGN KEY ("U_RATE_TYPE")
	  REFERENCES "SCPOMGR"."UDT_RATE_TYPE" ("U_RATE_TYPE") ENABLE;
