--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDT_EQUIPMENT_CONVERSION
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" 
   (	"COMPANYID" VARCHAR2(50 BYTE) DEFAULT ' ', 
	"U_AREA" VARCHAR2(50 BYTE) DEFAULT ' ', 
	"EQUIPMENT_NATIVE" VARCHAR2(50 BYTE) DEFAULT ' ', 
	"U_EQUIPMENT_TYPE" VARCHAR2(20 BYTE) DEFAULT ' '
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;

   COMMENT ON COLUMN "SCPOMGR"."UDT_EQUIPMENT_CONVERSION"."U_AREA" IS 'This matches the value in the U_AREA table';
   COMMENT ON COLUMN "SCPOMGR"."UDT_EQUIPMENT_CONVERSION"."EQUIPMENT_NATIVE" IS 'This is the Actual Rquipment type as it comes from Seibel.';
   COMMENT ON COLUMN "SCPOMGR"."UDT_EQUIPMENT_CONVERSION"."U_EQUIPMENT_TYPE" IS 'This is the Value of general equipment type. I.E. FB or VN. Loc.U_Equipment_Type will be updated with this value and it will be used when accesing the UDT_COST_TRANSIT table.';
--------------------------------------------------------
--  DDL for Index UDT_EQUIPMENT_CONVERSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_EQUIPMENT_CONVERSION_PK" ON "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ("COMPANYID", "U_AREA", "EQUIPMENT_NATIVE", "U_EQUIPMENT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_EQUIPMENT_CONVERSION_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_EQUIPMENT_CONVERSION_IDX" ON "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ("U_AREA", "EQUIPMENT_NATIVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table UDT_EQUIPMENT_CONVERSION
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("EQUIPMENT_NATIVE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("U_AREA" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("COMPANYID" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ADD CONSTRAINT "UDT_EQUIPMENT_CONVERSION_PK" PRIMARY KEY ("COMPANYID", "U_AREA", "EQUIPMENT_NATIVE", "U_EQUIPMENT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UDT_EQUIPMENT_CONVERSION
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ADD CONSTRAINT "UDT_EQUIPMENT_CONVERSION__FK1" FOREIGN KEY ("U_EQUIPMENT_TYPE")
	  REFERENCES "SCPOMGR"."UDT_EQUIPMENT_TYPE" ("U_EQUIPMENT_TYPE") ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ADD CONSTRAINT "UDT_EQUIPMENT_CONVERSION__FK2" FOREIGN KEY ("COMPANYID")
	  REFERENCES "SCPOMGR"."UDT_AREA" ("COMPANYID") ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ADD CONSTRAINT "UDT_EQUIPMENT_CONVERSION__FK3" FOREIGN KEY ("U_AREA")
	  REFERENCES "SCPOMGR"."UDT_AREA_TYPE" ("U_AREA") ENABLE;
