--------------------------------------------------------
--  Constraints for Table UDT_GIDLIMITS_NA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" ADD CONSTRAINT "UDT_GIDLIMITS_NA_PK" PRIMARY KEY ("PRIMARY_KEY_COL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" MODIFY ("U_LOC_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" MODIFY ("PRIMARY_KEY_COL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" MODIFY ("LOC" NOT NULL ENABLE)
