--------------------------------------------------------
--  DDL for Table UDT_ACTIVE_SITES_TEMP
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_ACTIVE_SITES_TEMP" 
   (	"LOC" VARCHAR2(30 CHAR), 
	"RES" VARCHAR2(30 CHAR), 
	"STATUS" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
