--------------------------------------------------------
--  Ref Constraints for Table UDT_PLANT_STATUS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDC_PLANT_STATUS_FK2" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."UDT_PLANT_CAPABILITIES" ("CAPABILITY") ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDT_PLANT_STATUS_FK1" FOREIGN KEY ("LOC")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") DISABLE;
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDT_PLANT_STATUS_UDT_EQUI_FK1" FOREIGN KEY ("U_EQUIPMENT_TYPE")
	  REFERENCES "SCPOMGR"."UDT_EQUIPMENT_TYPE" ("U_EQUIPMENT_TYPE") ENABLE;
