--------------------------------------------------------
--  Constraints for Table UDT_RESOURCE_WEEKLY_UTIL
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_RESOURCE_WEEKLY_UTIL" ADD CONSTRAINT "UDT_RESOURCE_WEEKLY_UTIL_PK" PRIMARY KEY ("RES", "EFF")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_RESOURCE_WEEKLY_UTIL" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESOURCE_WEEKLY_UTIL" MODIFY ("RES" NOT NULL ENABLE)
