--------------------------------------------------------
--  Constraints for Table UDT_SKUMETRIC_WK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_WK" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_WK" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_WK" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_WK" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_WK" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_WK" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_WK" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SKUMETRIC_WK" MODIFY ("EFF" NOT NULL ENABLE)
