--------------------------------------------------------
--  Constraints for Table UDT_RESMETRIC_ALT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("SETUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("TIMEUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_ALT" MODIFY ("EFF" NOT NULL ENABLE)
