--------------------------------------------------------
--  Constraints for Table UDT_COST_TRANSIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANIST_NEW_PK" PRIMARY KEY ("DIRECTION", "U_EQUIPMENT_TYPE", "SOURCE_PC", "DEST_PC", "SOURCE_GEO", "DEST_GEO", "SOURCE_CO", "DEST_CO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_SPC_CHK1" CHECK ((TRIM(SOURCE_PC) IS NOT NULL AND TRIM(SOURCE_GEO) IS NULL) OR (TRIM(SOURCE_PC) IS NULL AND TRIM(SOURCE_GEO) IS NOT NULL)) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANSIT_DPC_CHK1" CHECK ((TRIM(DEST_PC) IS NOT NULL AND TRIM(DEST_GEO) IS NULL) OR (TRIM(DEST_PC) IS NULL AND TRIM(DEST_GEO) IS NOT NULL)) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANIST_TRTM_CHK2" CHECK (TRANSITTIME >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANIST_PAL_CHK3" CHECK (COST_PALLET >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" ADD CONSTRAINT "UDT_COST_TRANIST_COST_CHK4" CHECK (COST_KM >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("LANE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DEST_GEO" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("SOURCE_GEO" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DISTANCE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("COST_PALLET" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("COST_KM" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("TRANSITTIME" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("SALESGROUP" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DEST_PC" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DEST_CO" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("SOURCE_PC" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("SOURCE_CO" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT" MODIFY ("DIRECTION" NOT NULL ENABLE);
