--------------------------------------------------------
--  DDL for Table UDT_DFUVIEW_ABC_CLASS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_DFUVIEW_ABC_CLASS" 
   (	"COUNTRY" VARCHAR2(50 CHAR), 
	"DMDUNIT" VARCHAR2(50 CHAR), 
	"DMDGROUP" VARCHAR2(50 CHAR), 
	"LOC" VARCHAR2(50 CHAR), 
	"CUMULATIVE_PERCENT" FLOAT(126), 
	"ABC_CLASS" VARCHAR2(50 CHAR), 
	"MATERIAL_CODE" VARCHAR2(10 CHAR), 
	"U_DFULEVEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
