--------------------------------------------------------
--  Constraints for Table UDT_TERRITORY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_TERRITORY" ADD PRIMARY KEY ("POSTALCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_TERRITORY" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_TERRITORY" MODIFY ("CLUSTERCODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_TERRITORY" MODIFY ("TERRITORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_TERRITORY" MODIFY ("COUNTRY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_TERRITORY" MODIFY ("POSTALCODE" NOT NULL ENABLE)
