--------------------------------------------------------
--  Constraints for Table UDT_PLANT_STATUS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("U_STOCK" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("U_MATERIALCODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDT_PLANT_STATUS_PK" PRIMARY KEY ("LOC", "U_MATERIALCODE", "U_STOCK", "RES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDT_PLANT_STATUS_CHK1" CHECK (STATUS IN ('0', '1')) ENABLE
