--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDT_PLANT_STATUS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_PLANT_STATUS" 
   (	"LOC" VARCHAR2(30 CHAR), 
	"U_MATERIALCODE" VARCHAR2(30 CHAR), 
	"U_STOCK" VARCHAR2(30 CHAR), 
	"RES" VARCHAR2(30 CHAR), 
	"STATUS" VARCHAR2(30 CHAR), 
	"U_EQUIPMENT_TYPE" VARCHAR2(50 BYTE) DEFAULT ' '
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_PLANT_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_PLANT_STATUS_PK" ON "SCPOMGR"."UDT_PLANT_STATUS" ("LOC", "U_MATERIALCODE", "U_STOCK", "RES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  DDL for Index UDT_PLANT_STATUS_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_PLANT_STATUS_INDEX1" ON "SCPOMGR"."UDT_PLANT_STATUS" ("LOC", "RES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table UDT_PLANT_STATUS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("RES" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("U_STOCK" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("U_MATERIALCODE" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" MODIFY ("LOC" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDT_PLANT_STATUS_PK" PRIMARY KEY ("LOC", "U_MATERIALCODE", "U_STOCK", "RES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDT_PLANT_STATUS_CHK1" CHECK (STATUS IN ('0', '1')) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UDT_PLANT_STATUS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDC_PLANT_STATUS_FK2" FOREIGN KEY ("RES")
	  REFERENCES "SCPOMGR"."UDT_PLANT_CAPABILITIES" ("CAPABILITY") ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDT_PLANT_STATUS_FK1" FOREIGN KEY ("LOC")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") DISABLE;
  ALTER TABLE "SCPOMGR"."UDT_PLANT_STATUS" ADD CONSTRAINT "UDT_PLANT_STATUS_UDT_EQUI_FK1" FOREIGN KEY ("U_EQUIPMENT_TYPE")
	  REFERENCES "SCPOMGR"."UDT_EQUIPMENT_TYPE" ("U_EQUIPMENT_TYPE") ENABLE;
