--------------------------------------------------------
--  Constraints for Table UDT_COST_TRANSIT_DUMMY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("LANE_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("DEST_GEO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("SOURCE_GEO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("DISTANCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("COST_PALLET" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("COST_KM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("TRANSITTIME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("SALESGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("DEST_PC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("DEST_CO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("SOURCE_PC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("SOURCE_CO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_DUMMY" MODIFY ("DIRECTION" NOT NULL ENABLE)
