--------------------------------------------------------
--  Constraints for Table UDT_RESMETRIC_WK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("SETUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("TIMEUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_WK" MODIFY ("EFF" NOT NULL ENABLE)
