--------------------------------------------------------
--  Constraints for Table UDT_P1_DATA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("CT_DIR" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("CT_ET" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("SM_SOURCING" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("CT_TLT" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("CT_COST" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("CT_DEST_PC" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("CT_SOURCE_PC" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("LS_SRC" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("LS_DEST" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_P1_DATA" MODIFY ("LS_ITEM" NOT NULL ENABLE);
