--------------------------------------------------------
--  Constraints for Table UDT_STATE_ABBREVIATIONS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_STATE_ABBREVIATIONS" MODIFY ("COUNTRY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_STATE_ABBREVIATIONS" ADD CONSTRAINT "UDT_STATE_ABBREVIATIONS_PK" PRIMARY KEY ("ABBREV")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_STATE_ABBREVIATIONS" MODIFY ("ABBREV" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_STATE_ABBREVIATIONS" MODIFY ("STATE" NOT NULL ENABLE)
