--------------------------------------------------------
--  Constraints for Table UDT_YIELDRATE_BKP_15SEP2015
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("DOCDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("QUANTITY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("PSTDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("PURCHORDER" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("MATDOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("USERNAME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("MVTTYPETEXT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("MVT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("SLOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("BATCH" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("MATERIAL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELDRATE_BKP_15SEP2015" MODIFY ("PLANT" NOT NULL ENABLE)
