--------------------------------------------------------
--  Constraints for Table UDT_FIXED_COLL
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_FIXED_COLL" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_FIXED_COLL" ADD CONSTRAINT "UDT_FIXED_COLL_PK" PRIMARY KEY ("LOC", "PLANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_FIXED_COLL" MODIFY ("PLANT" NOT NULL ENABLE)
