--------------------------------------------------------
--  Constraints for Table UDT_TPM_CORRECTIONS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_TPM_CORRECTIONS" ADD CONSTRAINT "UDT_TPM_CORRECTIONS_PK" PRIMARY KEY ("LOC", "ITEM", "EFF", "CATEGORY")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_TPM_CORRECTIONS" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_TPM_CORRECTIONS" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_TPM_CORRECTIONS" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_TPM_CORRECTIONS" MODIFY ("LOC" NOT NULL ENABLE)
