--------------------------------------------------------
--  Constraints for Table UDT_RESOURCE_UTIL
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_RESOURCE_UTIL" ADD CONSTRAINT "UDT_RESOURCE_UTIL_PK" PRIMARY KEY ("RES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_RESOURCE_UTIL" MODIFY ("RES" NOT NULL ENABLE)
