--------------------------------------------------------
--  Constraints for Table UDT_DFUTOSKUFCST_WK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("SUPERSEDESW" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("TOTFCST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("STARTDATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("DFULOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("DMDGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("DMDUNIT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("SKULOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DFUTOSKUFCST_WK" MODIFY ("ITEM" NOT NULL ENABLE)
