--------------------------------------------------------
--  Constraints for Table UDT_YIELD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_PK" PRIMARY KEY ("LOC", "ITEM", "PRODUCTIONMETHOD")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_C03" CHECK (MINHRSPERDAY <= MAXHRSPERDAY AND MINDAYSPERWK <=MAXDAYSPERWK) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_C02" CHECK (MINCAP <= MAXCAP) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CONSTRAINT "UDT_YIELD_C01" CHECK (DND IN (1, 0)) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD" ADD CHECK (EFFICIENCY > 0) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("DND" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("YIELD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MINCAP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MAXCAP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MINDAYSPERWK" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MAXDAYSPERWK" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MINHRSPERDAY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MAXHRSPERDAY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("EFFICIENCY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("QB" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD" MODIFY ("MATCODE" NOT NULL ENABLE)
