--------------------------------------------------------
--  DDL for Index UDT_EQUIPMENT_CONVERSION_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_EQUIPMENT_CONVERSION_IDX" ON "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ("U_AREA", "EQUIPMENT_NATIVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
