--------------------------------------------------------
--  DDL for Index UDT_LAMMASOFT_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_LAMMASOFT_DATA_PK" ON "SCPOMGR"."UDT_LLAMASOFT_DATA" ("ITEM", "SOURCE", "DEST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
