--------------------------------------------------------
--  DDL for Table UDT_COUNTRY_ABC_CLASS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_COUNTRY_ABC_CLASS" 
   (	"COUNTRY" VARCHAR2(50 CHAR), 
	"ABC_CLASS" VARCHAR2(50 CHAR), 
	"VOL_PERCENT_BEGIN" NUMBER(10,0), 
	"VOL_PERCENT_END" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
