--------------------------------------------------------
--  Constraints for Table UDT_YIELD_TMP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("DND" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("YIELD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("MINCAP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("MAXCAP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("MINDAYSPERWK" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("MAXDAYSPERWK" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("MINHRSPERDAY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("MAXHRSPERDAY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("EFFICIENCY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("QB" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_YIELD_TMP" MODIFY ("MATCODE" NOT NULL ENABLE)
