--------------------------------------------------------
--  Constraints for Table UDT_SOURCINGMETRIC_ALT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_ALT" MODIFY ("SOURCING" NOT NULL ENABLE)
