--------------------------------------------------------
--  Constraints for Table UDT_RESMETRIC_RB
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("SETUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("TIMEUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_RESMETRIC_RB" MODIFY ("EFF" NOT NULL ENABLE)
