--------------------------------------------------------
--  Constraints for Table UDT_COST_UNIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" ADD CONSTRAINT "UDT_COST_UNIT_PK" PRIMARY KEY ("LOC", "MATCODE", "PROCESS")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" ADD CONSTRAINT "UDT_COST_UNIT_C01" CHECK (UNIT_COST >= 0) ENABLE
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("UNIT_COST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("COMPANY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("LOC" NOT NULL ENABLE)
