--------------------------------------------------------
--  Constraints for Table UDT_EQUIPMENT_CONVERSION
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("EQUIPMENT_NATIVE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("U_AREA" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" MODIFY ("COMPANYID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_CONVERSION" ADD CONSTRAINT "UDT_EQUIPMENT_CONVERSION_PK" PRIMARY KEY ("COMPANYID", "U_AREA", "EQUIPMENT_NATIVE", "U_EQUIPMENT_TYPE")
  USING INDEX  ENABLE
