--------------------------------------------------------
--  Constraints for Table UDT_LOC_TYPE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_LOC_TYPE" ADD CONSTRAINT "UDT_LOC_TYPE_PK" PRIMARY KEY ("LOC_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_LOC_TYPE" MODIFY ("LOC_TYPE" NOT NULL ENABLE);
