--------------------------------------------------------
--  Constraints for Table UDT_PRODUCTIONRESMETRIC_WK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_WK" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
