--------------------------------------------------------
--  Constraints for Table UDT_COST_TRANSIT_BKP_28AUG15
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("LANE_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("DEST_GEO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("SOURCE_GEO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("DISTANCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("COST_PALLET" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("COST_KM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("TRANSITTIME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("SALESGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("DEST_PC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("DEST_CO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("SOURCE_PC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("SOURCE_CO" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_COST_TRANSIT_BKP_28AUG15" MODIFY ("DIRECTION" NOT NULL ENABLE)
