--------------------------------------------------------
--  Constraints for Table UDT_EQUIPMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_TYPE" ADD CONSTRAINT "UDT_EQUIPMENT_TYPE_PK" PRIMARY KEY ("U_EQUIPMENT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_EQUIPMENT_TYPE" MODIFY ("U_EQUIPMENT_TYPE" NOT NULL ENABLE);
