--------------------------------------------------------
--  Constraints for Table UDT_SOURCINGMETRIC_WK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" ADD CONSTRAINT "PK_UDT_SOURCINGMETRIC_WK" PRIMARY KEY ("ITEM", "DEST", "SOURCE", "SOURCING", "EFF", "CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGMETRIC_WK" MODIFY ("SOURCING" NOT NULL ENABLE)
