--------------------------------------------------------
--  DDL for Table UDT_SRCLIMITS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_SRCLIMITS" 
   (	"DEST_COUNTRY" VARCHAR2(25 CHAR), 
	"LIMIT" VARCHAR2(25 CHAR), 
	"MATCODE" VARCHAR2(5 CHAR), 
	"QB" VARCHAR2(25 CHAR), 
	"RULE" NUMBER(*,0), 
	"SRC_COUNTRY" VARCHAR2(5 CHAR), 
	"SRC_SC" VARCHAR2(5 CHAR), 
	"PRIMARY_KEY_COL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
