--------------------------------------------------------
--  Constraints for Table UDT_SOURCINGRESMETRIC_WK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_SOURCINGRESMETRIC_WK" MODIFY ("SOURCING" NOT NULL ENABLE)
