--------------------------------------------------------
--  Constraints for Table UDT_COST_UNIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" ADD CONSTRAINT "UDT_COST_UNIT_PK" PRIMARY KEY ("LOC", "MATCODE", "PROCESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" ADD CONSTRAINT "UDT_COST_UNIT_C01" CHECK (UNIT_COST >= 0) ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("UNIT_COST" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("COMPANY" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_COST_UNIT" MODIFY ("LOC" NOT NULL ENABLE);
