--------------------------------------------------------
--  DDL for Table UDT_YIELD_TIMEPHASE
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_YIELD_TIMEPHASE" 
   (	"EFF" DATE, 
	"MINCAP" NUMBER(*,0), 
	"MAXCAP" NUMBER(*,0), 
	"DUR" VARCHAR2(4 CHAR), 
	"RES" VARCHAR2(25 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
