--------------------------------------------------------
--  DDL for Table UDT_DEFAULT_PARAMETERS
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_DEFAULT_PARAMETERS" 
   (	"NAME" VARCHAR2(50) DEFAULT ' ', 
	"DESCRIPTION" VARCHAR2(100) DEFAULT ' ', 
	"CHRVAL1" VARCHAR2(50) DEFAULT ' ', 
	"NUMVAL1" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
