--------------------------------------------------------
--  Constraints for Table UDT_GIDLIMITS_NA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" ADD CONSTRAINT "UDT_GIDLIMITS_NA_PK" PRIMARY KEY ("PRIMARY_KEY_COL")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" MODIFY ("U_LOC_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" MODIFY ("PRIMARY_KEY_COL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" MODIFY ("LOC" NOT NULL ENABLE)
