--------------------------------------------------------
--  Constraints for Table UDT_STOCK_TARGET
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_STOCK_TARGET" ADD CONSTRAINT "PK_UDT_STOCK_TARGET" PRIMARY KEY ("LOC", "MATCODE", "STOCK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_STOCK_TARGET" MODIFY ("STOCK" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_STOCK_TARGET" MODIFY ("MATCODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_STOCK_TARGET" MODIFY ("LOC" NOT NULL ENABLE)
