--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UDT_PLANT_CAPABILITIES
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_PLANT_CAPABILITIES" 
   (	"CAPABILITY" VARCHAR2(30 CHAR), 
	"STATUS" VARCHAR2(30 CHAR), 
	"DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;

   COMMENT ON COLUMN "SCPOMGR"."UDT_PLANT_CAPABILITIES"."DESCRIPTION" IS 'Should be set to non nullable later.';
--------------------------------------------------------
--  DDL for Index UDT_CAPACITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."UDT_CAPACITIES_PK" ON "SCPOMGR"."UDT_PLANT_CAPABILITIES" ("CAPABILITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA" ;
--------------------------------------------------------
--  Constraints for Table UDT_PLANT_CAPABILITIES
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PLANT_CAPABILITIES" ADD CONSTRAINT "UDT_CAPACITIES_PK" PRIMARY KEY ("CAPABILITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"  ENABLE;
  ALTER TABLE "SCPOMGR"."UDT_PLANT_CAPABILITIES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCPOMGR"."UDT_PLANT_CAPABILITIES" MODIFY ("CAPABILITY" NOT NULL ENABLE);
