--------------------------------------------------------
--  Ref Constraints for Table UDT_GIDLIMITS_NA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" ADD CONSTRAINT "UDT_GIDLIMITS_NA_ITEM_FK1" FOREIGN KEY ("ITEM")
	  REFERENCES "SCPOMGR"."ITEM" ("ITEM") ENABLE
  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" ADD CONSTRAINT "UDT_GIDLIMITS_NA_LOC_FK1" FOREIGN KEY ("MANDATORY_LOC")
	  REFERENCES "SCPOMGR"."LOC" ("LOC") ENABLE
  ALTER TABLE "SCPOMGR"."UDT_GIDLIMITS_NA" ADD CONSTRAINT "UDT_GIDLIMITS_NA_UDT_LOC__FK1" FOREIGN KEY ("U_LOC_TYPE")
	  REFERENCES "SCPOMGR"."UDT_LOC_TYPE" ("LOC_TYPE") ENABLE
