--------------------------------------------------------
--  DDL for Table UDT_YIELD_TMP
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."UDT_YIELD_TMP" 
   (	"LOC" VARCHAR2(4 CHAR), 
	"MATCODE" VARCHAR2(5 CHAR), 
	"QB" VARCHAR2(14 CHAR), 
	"ITEM" VARCHAR2(15 CHAR), 
	"PRODUCTIONMETHOD" VARCHAR2(3 CHAR), 
	"EFFICIENCY" NUMBER, 
	"MAXHRSPERDAY" NUMBER, 
	"MINHRSPERDAY" NUMBER, 
	"MAXDAYSPERWK" NUMBER, 
	"MINDAYSPERWK" NUMBER, 
	"MAXCAP" NUMBER, 
	"MINCAP" NUMBER, 
	"YIELD" NUMBER, 
	"DND" NUMBER(*,0)
   )
