--------------------------------------------------------
--  Constraints for Table UDT_DEFAULT_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_DEFAULT_PARAMETERS" ADD CONSTRAINT "UDT_DEFAULT_PARAMETERS_PK" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."UDT_DEFAULT_PARAMETERS" MODIFY ("CHRVAL1" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DEFAULT_PARAMETERS" MODIFY ("DESCRIPTION" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_DEFAULT_PARAMETERS" MODIFY ("NAME" NOT NULL ENABLE)
