--------------------------------------------------------
--  Constraints for Table UDT_PRODUCTIONRESMETRIC_RB
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("QTYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("CURRENCYUOM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("RES" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("DUR" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("VALUE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."UDT_PRODUCTIONRESMETRIC_RB" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
