--------------------------------------------------------
--  DDL for Index XIF1RESSUBTYPE_TRANS
--------------------------------------------------------

  CREATE INDEX "SCPOMGR"."XIF1RESSUBTYPE_TRANS" ON "SCPOMGR"."RESSUBTYPE_TRANS" ("SUBTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
