--------------------------------------------------------
--  DDL for Index XIF2PRODUCTIONMETHOD
--------------------------------------------------------

  CREATE INDEX "SCPOMGR"."XIF2PRODUCTIONMETHOD" ON "SCPOMGR"."PRODUCTIONMETHOD" ("LEADTIMECAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCPODATA"
