--------------------------------------------------------
--  DDL for Index XPKPRODUCTIONFAMILYRESMAP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."XPKPRODUCTIONFAMILYRESMAP" ON "SCPOMGR"."PRODUCTIONFAMILYRESMAP" ("ORGRES", "PRODFAMILY", "NEWRES", "SIMULATION_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"
