--------------------------------------------------------
--  DDL for Index XPKRESOSUPPLYDETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."XPKRESOSUPPLYDETAIL" ON "SCPOMGR"."RESOSUPPLYDETAIL" ("PROCESSID", "DMDORDERTYPE", "DMDORDERSEQNUM", "DMDNEEDDATE", "SUPPLYSEQNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"
