--------------------------------------------------------
--  DDL for Index XPKRESOINDEPENDENTDMD
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCPOMGR"."XPKRESOINDEPENDENTDMD" ON "SCPOMGR"."RESOINDEPENDENTDMD" ("PROCESSID", "DMDORDERTYPE", "DMDORDERSEQNUM", "NEEDDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SCPODATA"
