  DROP FUNCTION "SCPOMGR"."IS_3DIGIT";
  DROP FUNCTION "SCPOMGR"."IS_5DIGIT";
  DROP FUNCTION "SCPOMGR"."IS_NUMBER";
  DROP FUNCTION "SCPOMGR"."V_GET_COST";
  DROP FUNCTION "SCPOMGR"."V_GET_DIST";
  DROP FUNCTION "SCPOMGR"."V_INIT_EFF_DATE";
