SELECT SM.DEST, SM.ITEM,  SM.SOURCE, SM.EFF, ROUND(SM.VALUE) METQTY
    , round(skc.qty) DmdQty, SM.CATEGORY, SM.SOURCING
     
FROM SOURCINGMETRIC SM, SKUCONSTRAINT SKC
WHERE SM.DEST=SKC.LOC
  and sm.item=skc.item
  AND SM.EFF=SKC.EFF
  AND SKC.CATEGORY=1
order by dest, item, eff asc