--------------------------------------------------------
--  DDL for View SCHEDSUPPLYVIEW
--------------------------------------------------------

  CREATE OR REPLACE VIEW "SCPOMGR"."SCHEDSUPPLYVIEW" ("ORDERID", "SUPPLYTYPE", "EXTORDERID", "QTY", "QTYRECEIVED", "ITEM", "DEST", "SOURCE", "NEEDFINDATE", "NEEDSTARTDATE", "METHOD", "ACTIONSW", "SUPPLYSOURCEOPT", "DESTSTATUSOPT", "SOURCESTATUSOPT", "EXPLODESW", "LASTCOMPLETEDSTEP", "PCTCOMPLETE", "EXPDATE", "ACTION", "ACTIONDATE", "ACTIONQTY", "REVISEDDATE", "REVISEDEXPDATE") AS 
  SELECT  VLL.ORDERNUM ORDERID, 5 SUPPLYTYPE, VLL.LOADID EXTORDERID, VLL.QTY QTY,
        VLL.QTY QTYRECEIVED, VLL.ITEM ITEM, VLL.DEST DEST, VLL.SOURCE SOURCE,
        VL.ARRIVDATE NEEDFINDATE, VL.SHIPDATE NEEDSTARTDATE, VLL.SOURCING METHOD,
        VLL.ACTIONALLOWEDSW ACTIONSW, 0 SUPPLYSOURCEOPT, VL.DESTSTATUS DESTSTATUSOPT,
        VL.SOURCESTATUS SOURCESTATUSOPT, 0 EXPLODESW, 0 LASTCOMPLETEDSTEP, 0 PCTCOMPLETE,
        VLL.EXPDATE EXPDATE, VLL.ACTION ACTION, VLL.ACTIONDATE ACTIONDATE, VLL.ACTIONQTY ACTIONQTY,
        VLL.REVISEDDATE REVISEDDATE, VLL.REVISEDEXPDATE REVISEDEXPDATE
FROM    VEHICLELOAD VL, VEHICLELOADLINE VLL
WHERE   VL.LOADID = VLL.LOADID
UNION
SELECT  SR.ORDERNUM ORDERID, 6 SUPPLYTYPE, ' ' EXTORDERID, SR.QTY QTY, SR.QTYRECEIVED QTYRECEIVED,
        SR.ITEM ITEM, SR.LOC DEST, ' ' SOURCE, SR.SCHEDDATE NEEDFINDATE, SR.STARTDATE NEEDSTARTDATE,
        SR.PRODUCTIONMETHOD METHOD, SR.ACTIONALLOWEDSW ACTIONSW, 1 SUPPLYSOURCEOPT, 0 DESTSTATUSOPT,
        0 SOURCESTATUSOPT, SR.EXPLODESW EXPLODESW, SR.LASTCOMPLETEDSTEP LASTCOMPLETEDSTEP,
        SR.PCTCOMPLETE PCTCOMPLETE, SR.EXPDATE EXPDATE, SR.ACTION ACTION, SR.ACTIONDATE ACTIONDATE,
        SR.ACTIONQTY ACTIONQTY, SR.REVISEDDATE REVISEDDATE, SR.REVISEDEXPDATE REVISEDEXPDATE
FROM    SCHEDRCPTS SR
UNION
SELECT  PA.SEQNUM ORDERID, 11 SUPPLYTYPE, ' ' EXTORDERID, PA.QTY QTY, 0 QTYRECEIVED, PA.ITEM ITEM,
        PA.DEST DEST, PA.SOURCE SOURCE, PA.SCHEDARRIVDATE NEEDFINDATE, PA.SCHEDSHIPDATE NEEDSTARTDATE,
        PA.SOURCING METHOD, PA.ACTIONALLOWEDSW ACTIONSW, 0 SUPPLYSOURCEOPT, 0 DESTSTATUSOPT,
        0 SOURCESTATUSOPT, 0 EXPLODESW, 0 LASTCOMPLETEDSTEP, 0 PCTCOMPLETE, PA.EXPDATE EXPDATE,
        PA.ACTION ACTION, PA.ACTIONDATE ACTIONDATE, PA.ACTIONQTY ACTIONQTY, PA.REVISEDDATE REVISEDDATE,
        PA.REVISEDEXPDATE REVISEDEXPDATE
FROM    PLANARRIV PA
WHERE   PA.FIRMPLANSW = 1
UNION
SELECT  PO.SEQNUM ORDERID, 9 SUPPLYTYPE, ' ' EXTORDERID, PO.QTY QTY, 0 QTYRECEIVED, PO.ITEM ITEM,
        PO.LOC DEST, ' ' SOURCE, PO.SCHEDDATE NEEDFINDATE, PO.STARTDATE NEEDSTARTDATE,
        PO.PRODUCTIONMETHOD METHOD, PO.ACTIONALLOWEDSW ACTIONSW, 1 SUPPLYSOURCEOPT, 0 DESTSTATUSOPT,
        0 SOURCESTATUSOPT, 0 EXPLODESW, 0 LASTCOMPLETEDSTEP, 0 PCTCOMPLETE, PO.EXPDATE EXPDATE,
        PO.ACTION ACTION, PO.ACTIONDATE ACTIONDATE, PO.ACTIONQTY ACTIONQTY, PO.REVISEDDATE REVISEDDATE,
        PO.REVISEDEXPDATE REVISEDEXPDATE
FROM    PLANORDER PO
WHERE   PO.FIRMPLANSW = 1
UNION
SELECT  PP.SEQNUM ORDERID, 13 SUPPLYTYPE, ' ' EXTORDERID, PP.QTY QTY,0 QTYRECEIVED, PP.ITEM ITEM,
        PP.LOC DEST, ' ' SOURCE, PP.SCHEDDATE NEEDFINDATE, PP.STARTDATE NEEDSTARTDATE, PP.PURCHMETHOD METHOD,
        PP.ACTIONALLOWEDSW ACTIONSW, 3 SUPPLYSOURCEOPT, 0 DESTSTATUSOPT, 0 SOURCESTATUSOPT, 0 EXPLODESW,
        0 LASTCOMPLETEDSTEP, 0 PCTCOMPLETE, PP.EXPDATE EXPDATE, PP.ACTION ACTION, PP.ACTIONDATE ACTIONDATE,
        PP.ACTIONQTY ACTIONQTY, PP.REVISEDDATE REVISEDDATE, TO_DATE ('01-01-1970', 'mm-dd-yyyy') REVISEDEXPDATE
FROM    PLANPURCH PP
WHERE   PP.FIRMPLANSW = 1
UNION
SELECT  PUO.ORDERSEQNUM ORDERID, 14 SUPPLYTYPE, ' ' EXTORDERID, PUO.QTY QTY, 0 QTYRECEIVED, PUO.ITEM ITEM,
        PUO.LOC DEST, ' ' SOURCE, PUO.DUEDATE NEEDFINDATE, PUO.DUEDATE NEEDSTARTDATE, PUO.PURCHMETHOD METHOD,
        PUO.FIRMSW ACTIONSW, 3 SUPPLYSOURCEOPT, 0 DESTSTATUSOPT, 0 SOURCESTATUSOPT, 0 EXPLODESW,
        0 LASTCOMPLETEDSTEP, 0 PCTCOMPLETE, PUO.EXPDATE EXPDATE, PUO.ACTION ACTION, PUO.ACTIONDATE ACTIONDATE,
        PUO.ACTIONQTY ACTIONQTY, TO_DATE ('01-01-1970', 'mm-dd-yyyy') REVISEDDATE,
        TO_DATE ('01-01-1970', 'mm-dd-yyyy') REVISEDEXPDATE
FROM    PURCHORDER PUO
