--------------------------------------------------------
--  DDL for Procedure U_BACKUP_VIEWS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "SCPOMGR"."U_BACKUP_VIEWS" as 
begin

execute immediate drop table SCPOMGR.MAK_SKUCONSTR_COLL_MISSING;

drop table SCPOMGR.MAK_SKUCONSTR_NO_3DIGIT_COLL;

drop table MAK_SKUCONSTR_NO_3ZIP_COSTTRN;

drop table SCPOMGR.MAK_SKUCONSTR_NO_3ZIP_SUMMARY;

drop table MAK_SKUCONSTR_NO_5ZIP_COL;

drop table SCPOMGR.MAK_SKUCONSTR_NO_5ZIP_COSTTRN;

drop table SCPOMGR.MAK_SKUCONSTR_NO_PC_SUMMARY;

drop table SCPOMGR.MAK_SKUCONSTR_SRC_MISSING;


create table SCPOMGR.MAK_SKUCONSTR_COLL_MISSING
as select * from SCPOMGR.SKUCONSTR_COLL_MISSING;

create table SCPOMGR.MAK_SKUCONSTR_NO_3DIGIT_COLL
as select * from SCPOMGR.SKUCONSTR_NO_3DIGIT_COLL;

create table SCPOMGR.MAK_SKUCONSTR_NO_3ZIP_COSTTRN
as select * from SCPOMGR.SKUCONSTR_NO_3DIGIT_COSTTRN;

create table SCPOMGR.MAK_SKUCONSTR_NO_3ZIP_SUMMARY
as select * from SCPOMGR.SKUCONSTR_NO_3DIGIT_SUMMARY;

create table SCPOMGR.MAK_SKUCONSTR_NO_5ZIP_COLL
as select * from SCPOMGR.SKUCONSTR_NO_5DIGIT_COLLECTION;


create table SCPOMGR.MAK_SKUCONSTR_NO_5ZIP_COSTTRN
as select * from SCPOMGR.SKUCONSTR_NO_5DIGIT_COSTTRN;

create table SCPOMGR.MAK_SKUCONSTR_NO_5ZIP_COSTTRN
as select * from SCPOMGR.SKUCONSTR_NO_5DIGIT_COSTTRN;

create table SCPOMGR.MAK_SKUCONSTR_NO_PC_SUMMARY
as select * from SCPOMGR.SKUCONSTR_NO_PC_SUMMARY;

create table SCPOMGR.MAK_SKUCONSTR_SRC_ALL
as select * from SCPOMGR.SKUCONSTR_SRC_ALL;

create table SCPOMGR.MAK_SKUCONSTR_SRC_MISSING
as select * from SCPOMGR.SKUCONSTR_SRC_MISSING;

end;

/

