--------------------------------------------------------
--  Constraints for Table KEY_UDT_DIRECTION
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_DIRECTION" ADD CONSTRAINT "XPKKEY_UDT_DIRECTION" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "U_DIRECTION")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_DIRECTION" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DIRECTION" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DIRECTION" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DIRECTION" MODIFY ("U_DIRECTION" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DIRECTION" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DIRECTION" MODIFY ("KEY_ID" NOT NULL ENABLE)
