--------------------------------------------------------
--  Constraints for Table KEY_UDT_TRANSLATE_DMDUNIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_TRANSLATE_DMDUNIT" ADD CONSTRAINT "XPKKEY_UDT_TRANSLATE_DMDUNIT" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "U_SAP_IDENTIFIER")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_TRANSLATE_DMDUNIT" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_TRANSLATE_DMDUNIT" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_TRANSLATE_DMDUNIT" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_TRANSLATE_DMDUNIT" MODIFY ("U_SAP_IDENTIFIER" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_TRANSLATE_DMDUNIT" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_TRANSLATE_DMDUNIT" MODIFY ("KEY_ID" NOT NULL ENABLE)
