--------------------------------------------------------
--  Constraints for Table KEY_UDT_DEFAULT_ZIP
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_ZIP" ADD CONSTRAINT "XPKKEY_UDT_DEFAULT_ZIP" PRIMARY KEY ("KEY_ID", "KEY_TYPE")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_ZIP" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_ZIP" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_ZIP" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_ZIP" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_ZIP" MODIFY ("KEY_ID" NOT NULL ENABLE)
