--------------------------------------------------------
--  Constraints for Table KEY_UDT_COUNTRY_ABC_CLASS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_ABC_CLASS" ADD CONSTRAINT "XPKKEY_UDT_COUNTRY_ABC_CLASS" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "ABC_CLASS", "COUNTRY")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_ABC_CLASS" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_ABC_CLASS" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_ABC_CLASS" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_ABC_CLASS" MODIFY ("COUNTRY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_ABC_CLASS" MODIFY ("ABC_CLASS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_ABC_CLASS" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_ABC_CLASS" MODIFY ("KEY_ID" NOT NULL ENABLE)
