--------------------------------------------------------
--  Constraints for Table KEY_UDT_LOC_TYPE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_LOC_TYPE" ADD CONSTRAINT "XPKKEY_UDT_LOC_TYPE" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "LOC_TYPE")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_LOC_TYPE" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LOC_TYPE" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LOC_TYPE" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LOC_TYPE" MODIFY ("LOC_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LOC_TYPE" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LOC_TYPE" MODIFY ("KEY_ID" NOT NULL ENABLE)
