--------------------------------------------------------
--  Constraints for Table KEY_UDT_DEFAULT_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_PARAMETERS" ADD CONSTRAINT "XPKKEY_UDT_DEFAULT_PARAMETERS" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "NAME")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_PARAMETERS" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_PARAMETERS" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_PARAMETERS" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_PARAMETERS" MODIFY ("NAME" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_PARAMETERS" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DEFAULT_PARAMETERS" MODIFY ("KEY_ID" NOT NULL ENABLE)
