--------------------------------------------------------
--  Constraints for Table KEY_UDT_GIDLIMITS_NA
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS_NA" ADD CONSTRAINT "XPKKEY_UDT_GIDLIMITS_NA" PRIMARY KEY ("KEY_ID", "KEY_TYPE")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS_NA" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS_NA" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS_NA" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS_NA" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS_NA" MODIFY ("KEY_ID" NOT NULL ENABLE)
