--------------------------------------------------------
--  Constraints for Table KEY_UDT_GIDLIMITS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS" ADD CONSTRAINT "XPKKEY_UDT_GIDLIMITS" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "PRIMARY_KEY_COL")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS" MODIFY ("PRIMARY_KEY_COL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_GIDLIMITS" MODIFY ("KEY_ID" NOT NULL ENABLE)
