--------------------------------------------------------
--  Constraints for Table KEY_UDT_COUNTRY_MAT_QTY
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_MAT_QTY" ADD CONSTRAINT "XPKKEY_UDT_COUNTRY_MAT_QTY" PRIMARY KEY ("KEY_ID", "KEY_TYPE")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_MAT_QTY" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_MAT_QTY" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_MAT_QTY" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_MAT_QTY" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COUNTRY_MAT_QTY" MODIFY ("KEY_ID" NOT NULL ENABLE)
