--------------------------------------------------------
--  Constraints for Table KEY_UDT_YIELDRATE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELDRATE" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELDRATE" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELDRATE" MODIFY ("PRIMARY_KEY_COL" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELDRATE" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELDRATE" MODIFY ("KEY_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELDRATE" ADD CONSTRAINT "XPKKEY_UDT_YIELDRATE" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "PRIMARY_KEY_COL")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELDRATE" MODIFY ("VIEW_ID" NOT NULL ENABLE)
