--------------------------------------------------------
--  Constraints for Table KEY_UDT_SOURCINGMETRIC_WK
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" ADD CONSTRAINT "XPKKEY_UDT_SOURCINGMETRIC_WK" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "CATEGORY", "SOURCE", "SOURCING", "DEST", "ITEM", "EFF")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("EFF" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("DEST" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("SOURCING" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("SOURCE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("CATEGORY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_SOURCINGMETRIC_WK" MODIFY ("KEY_ID" NOT NULL ENABLE)
