--------------------------------------------------------
--  Constraints for Table KEY_UDT_YIELD
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" ADD CONSTRAINT "XPKKEY_UDT_YIELD" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "PRODUCTIONMETHOD", "ITEM", "LOC")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" MODIFY ("ITEM" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" MODIFY ("PRODUCTIONMETHOD" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_YIELD" MODIFY ("KEY_ID" NOT NULL ENABLE)
