--------------------------------------------------------
--  Constraints for Table KEY_UDT_FIXED_COLL
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_FIXED_COLL" ADD CONSTRAINT "XPKKEY_UDT_FIXED_COLL" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "PLANT", "LOC")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_FIXED_COLL" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_FIXED_COLL" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_FIXED_COLL" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_FIXED_COLL" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_FIXED_COLL" MODIFY ("PLANT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_FIXED_COLL" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_FIXED_COLL" MODIFY ("KEY_ID" NOT NULL ENABLE)
