--------------------------------------------------------
--  Constraints for Table KEY_UDT_COST_UNIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" ADD CONSTRAINT "XPKKEY_UDT_COST_UNIT" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "PROCESS", "MATCODE", "LOC")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" MODIFY ("MATCODE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" MODIFY ("PROCESS" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_COST_UNIT" MODIFY ("KEY_ID" NOT NULL ENABLE)
