--------------------------------------------------------
--  Constraints for Table KEY_UDT_DFUVIEW_ABC_CLASS
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" ADD CONSTRAINT "XPKKEY_UDT_DFUVIEW_ABC_CLASS" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "DMDGROUP", "COUNTRY", "DMDUNIT", "LOC")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("LOC" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("DMDUNIT" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("COUNTRY" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("DMDGROUP" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_DFUVIEW_ABC_CLASS" MODIFY ("KEY_ID" NOT NULL ENABLE)
