--------------------------------------------------------
--  Constraints for Table KEY_UDT_VIEW_TRANS_DMDUNIT
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_VIEW_TRANS_DMDUNIT" ADD CONSTRAINT "XPKKEY_UDT_VIEW_TRANS_DMDUNIT" PRIMARY KEY ("KEY_ID", "KEY_TYPE")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_VIEW_TRANS_DMDUNIT" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_VIEW_TRANS_DMDUNIT" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_VIEW_TRANS_DMDUNIT" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_VIEW_TRANS_DMDUNIT" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_VIEW_TRANS_DMDUNIT" MODIFY ("KEY_ID" NOT NULL ENABLE)
