--------------------------------------------------------
--  Constraints for Table KEY_UDT_RATE_TYPE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_RATE_TYPE" ADD CONSTRAINT "XPKKEY_UDT_RATE_TYPE" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "U_RATE_TYPE")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_RATE_TYPE" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_RATE_TYPE" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_RATE_TYPE" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_RATE_TYPE" MODIFY ("U_RATE_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_RATE_TYPE" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_RATE_TYPE" MODIFY ("KEY_ID" NOT NULL ENABLE)
