--------------------------------------------------------
--  Constraints for Table KEY_UDT_LANE_TYPE
--------------------------------------------------------

  ALTER TABLE "SCPOMGR"."KEY_UDT_LANE_TYPE" ADD CONSTRAINT "XPKKEY_UDT_LANE_TYPE" PRIMARY KEY ("KEY_ID", "KEY_TYPE", "LANE_TYPE")
  USING INDEX  ENABLE
  ALTER TABLE "SCPOMGR"."KEY_UDT_LANE_TYPE" MODIFY ("VIEW_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LANE_TYPE" MODIFY ("CREATE_DATE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LANE_TYPE" MODIFY ("SESSION_ID" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LANE_TYPE" MODIFY ("LANE_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LANE_TYPE" MODIFY ("KEY_TYPE" NOT NULL ENABLE)
  ALTER TABLE "SCPOMGR"."KEY_UDT_LANE_TYPE" MODIFY ("KEY_ID" NOT NULL ENABLE)
