--------------------------------------------------------
--  DDL for Table KEY_UDT_COST_TRANSIT
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."KEY_UDT_COST_TRANSIT" 
   (	"KEY_ID" FLOAT(126) DEFAULT 0, 
	"KEY_TYPE" CHAR(1 CHAR), 
	"DIRECTION" VARCHAR2(8 CHAR) DEFAULT ' ', 
	"SOURCE_CO" VARCHAR2(8 CHAR) DEFAULT ' ', 
	"SOURCE_PC" VARCHAR2(32 CHAR) DEFAULT ' ', 
	"DEST_GEO" VARCHAR2(12 CHAR) DEFAULT ' ', 
	"SOURCE_GEO" VARCHAR2(12 CHAR) DEFAULT ' ', 
	"U_EQUIPMENT_TYPE" VARCHAR2(50 CHAR) DEFAULT ' ', 
	"DEST_PC" VARCHAR2(32 CHAR) DEFAULT ' ', 
	"DEST_CO" VARCHAR2(8 CHAR) DEFAULT ' ', 
	"SESSION_ID" VARCHAR2(75 CHAR), 
	"CREATE_DATE" DATE, 
	"VIEW_ID" VARCHAR2(513 CHAR)
   )
