--------------------------------------------------------
--  DDL for Table KEY_UDT_COUNTRY_GLID_MAT_QTY
--------------------------------------------------------

  CREATE TABLE "SCPOMGR"."KEY_UDT_COUNTRY_GLID_MAT_QTY" 
   (	"KEY_ID" FLOAT(126) DEFAULT 0, 
	"KEY_TYPE" CHAR(1 CHAR), 
	"MATERIAL_CODE" VARCHAR2(200 CHAR), 
	"DMDGROUP" VARCHAR2(200 CHAR), 
	"GLID" VARCHAR2(200 CHAR), 
	"COUNTRY" VARCHAR2(200 CHAR), 
	"SESSION_ID" VARCHAR2(75 CHAR), 
	"CREATE_DATE" DATE, 
	"VIEW_ID" VARCHAR2(513 CHAR)
   )
